// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_settings_screen_init();
    ui_wifiset_screen_init();
    ui_connectwifi_screen_init();
    ui_soundset_screen_init();
    ui_langset_screen_init();
    ui_date_screen_init();
    ui_menu_screen_init();
     ui_employee_screen_init();
    ui_addemployee_screen_init();
    ui_editemployee_screen_init();
    ui_recordscreen_screen_init();
    ui_changepassscreen_screen_init();


    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}

void ui_destroy(void)
{
    ui_main_screen_destroy();
    ui_settings_screen_destroy();
    ui_wifiset_screen_destroy();
    ui_connectwifi_screen_destroy();
    ui_soundset_screen_destroy();
    ui_langset_screen_destroy();
    ui_date_screen_destroy();
    ui_menu_screen_destroy();
     ui_employee_screen_destroy();      
    ui_addemployee_screen_destroy();  
    ui_editemployee_screen_destroy();
    ui_recordscreen_screen_destroy();
    ui_changepassscreen_screen_destroy();

}

void ui_relocalize(void)
{
    ui_main_screen_relocalize();
    ui_settings_screen_relocalize();
    ui_wifiset_screen_relocalize();
    ui_connectwifi_screen_relocalize();
    ui_soundset_screen_relocalize();
    ui_langset_screen_relocalize();
    ui_date_screen_relocalize();
    ui_menu_screen_relocalize();
    ui_employee_screen_relocalize();      
    ui_addemployee_screen_relocalize(); 
    ui_editemployee_screen_relocalize();
    ui_recordscreen_screen_relocalize();
    ui_changepassscreen_screen_relocalize();



}
