// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_main.h"
#include "ui_settings.h"
#include "ui_wifiset.h"
#include "ui_connectwifi.h"
#include "ui_soundset.h"
#include "ui_langset.h"
#include "ui_date.h"
#include "ui_menu.h"
#include "ui_employee.h"
#include "ui_addemployee.h"
#include "ui_editemployee.h"
#include "ui_editemployee.h"
#include "ui_recordscreen.h"
#include "ui_changepassscreen.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_480x272_png);    // assets/background_480x272.png
LV_IMG_DECLARE(ui_img_724231620);    // assets/icons8-settings-24.png
LV_IMG_DECLARE(ui_img_706591335);    // assets/icons8-menu-32.png
LV_IMG_DECLARE(ui_img_1385604958);    // assets/icons8-left-22.png
LV_IMG_DECLARE(ui_img_567465477);    // assets/icons8-global-32.png
LV_IMG_DECLARE(ui_img_1687889417);    // assets/icons8-wifi-32.png
LV_IMG_DECLARE(ui_img_1475031593);    // assets/icons8-sound-32 (1).png
LV_IMG_DECLARE(ui_img_1198081141);    // assets/icons8-time-32.png
LV_IMG_DECLARE(ui_img_1958657997);    // assets/icons8-iphone-32.png
LV_IMG_DECLARE(ui_img_668791536);    // assets/icons8-info-32.png
LV_IMG_DECLARE(ui_img_1832640421);    // assets/icons8-forward-14.png
LV_IMG_DECLARE(ui_img_310155206);    // assets/icons8-search-20 (2).png
LV_IMG_DECLARE(ui_img_1799210772);    // assets/icons8-wifi-20.png
LV_IMG_DECLARE(ui_img_1176085953);    // assets/icons8-mute-sound-32.png
LV_IMG_DECLARE(ui_img_443122641);    // assets/icons8-touch-32.png
LV_IMG_DECLARE(ui_img_1790866911);    // assets/icons8-edit-22.png
LV_IMG_DECLARE(ui_img_1077457577); 
LV_IMG_DECLARE(ui_img_350414076);    // assets/icons8-employee-32.png
LV_IMG_DECLARE(ui_img_140600673);    // assets/icons8-key-32.png
LV_IMG_DECLARE(ui_img_1813113080);    // assets/icons8-shortlist-32.png
LV_IMG_DECLARE(ui_img_222311654);    // assets/icons8-fingerprint-50.png
LV_IMG_DECLARE(ui_img_565519698);    // assets/icons8-fingerprint-accepted-50.png
LV_IMG_DECLARE(ui_img_881979347);    // assets/icons8-fingerprint-error-50.png
LV_IMG_DECLARE(ui_img_670821478);    // assets/icons8-check-mark-50.png
LV_IMG_DECLARE(ui_img_1872894617);    // assets/icons8-wrong-50.png


// FONTS
LV_FONT_DECLARE(ui_font_arabic);
LV_FONT_DECLARE(ui_font_arabic1);
LV_FONT_DECLARE(ui_font_arabic12);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
