// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_plustxt8;
lv_obj_t * uic_Image110000;
lv_obj_t * uic_plustxt7;
lv_obj_t * uic_plustxt6;
lv_obj_t * uic_fingertemp4;
lv_obj_t * uic_plustxt5;
lv_obj_t * uic_fingertemp3;
lv_obj_t * uic_plustxt4;
lv_obj_t * uic_Image300;
lv_obj_t * uic_fingertemp;
lv_obj_t * uic_plustxt3;
lv_obj_t * uic_Image100;
lv_obj_t * uic_fingertemp2;
lv_obj_t * uic_mainpanel2;
lv_obj_t * uic_addemployeename;
lv_obj_t * uic_addemployeekey;
lv_obj_t * uic_addemployeetxt;
lv_obj_t * uic_plustxt;
lv_obj_t * uic_addemployeeaction;
lv_obj_t * uic_addemployee;
lv_obj_t * ui_addemployee = NULL;
lv_obj_t * ui_backtomenu3 = NULL;
lv_obj_t * ui_backimg3 = NULL;
lv_obj_t * ui_addemployeeaction = NULL;
lv_obj_t * ui_plustxt = NULL;
lv_obj_t * ui_addemployeetxt = NULL;
lv_obj_t * ui_addemployeekey = NULL;
lv_obj_t * ui_addemployeename = NULL;
lv_obj_t * ui_mainpanel2 = NULL;
lv_obj_t * ui_fingertemp2 = NULL;
lv_obj_t * ui_Image100 = NULL;
lv_obj_t * ui_plustxt3 = NULL;
lv_obj_t * ui_backtomenu4 = NULL;
lv_obj_t * ui_backimg4 = NULL;
lv_obj_t * ui_fingertemp = NULL;
lv_obj_t * ui_Image300 = NULL;
lv_obj_t * ui_plustxt4 = NULL;
lv_obj_t * ui_fingertemp3 = NULL;
lv_obj_t * ui_Image200 = NULL;
lv_obj_t * ui_plustxt5 = NULL;
lv_obj_t * ui_fingertemp4 = NULL;
lv_obj_t * ui_Image23113 = NULL;
lv_obj_t * ui_plustxt6 = NULL;
lv_obj_t * ui_fingertemp5 = NULL;
lv_obj_t * ui_Image2000 = NULL;
lv_obj_t * ui_plustxt7 = NULL;
lv_obj_t * ui_fingertemp6 = NULL;
lv_obj_t * ui_Image110000 = NULL;
lv_obj_t * ui_plustxt8 = NULL;
// event funtions
void ui_event_backtomenu3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_employee, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_employee_screen_init);
    }
}

void ui_event_backtomenu4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_employee, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_employee_screen_init);
    }
}

// build funtions

void ui_addemployee_screen_init(void)
{
    ui_addemployee = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_addemployee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_addemployee, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addemployee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtomenu3 = lv_button_create(ui_addemployee);
    lv_obj_set_width(ui_backtomenu3, 50);
    lv_obj_set_height(ui_backtomenu3, 38);
    lv_obj_set_x(ui_backtomenu3, -202);
    lv_obj_set_y(ui_backtomenu3, -114);
    lv_obj_set_align(ui_backtomenu3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu3, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg3 = lv_image_create(ui_backtomenu3);
    lv_image_set_src(ui_backimg3, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_addemployeeaction = lv_button_create(ui_addemployee);
    lv_obj_set_width(ui_addemployeeaction, 50);
    lv_obj_set_height(ui_addemployeeaction, 38);
    lv_obj_set_x(ui_addemployeeaction, 201);
    lv_obj_set_y(ui_addemployeeaction, -114);
    lv_obj_set_align(ui_addemployeeaction, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_addemployeeaction, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_addemployeeaction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_addemployeeaction, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_addemployeeaction, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addemployeeaction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_addemployeeaction, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_addemployeeaction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_addemployeeaction, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_addemployeeaction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_addemployeeaction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt = lv_label_create(ui_addemployeeaction);
    lv_obj_set_width(ui_plustxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt, "+");
    lv_obj_set_style_text_color(ui_plustxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addemployeetxt = lv_label_create(ui_addemployee);
    lv_obj_set_width(ui_addemployeetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_addemployeetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_addemployeetxt, 0);
    lv_obj_set_y(ui_addemployeetxt, -119);
    lv_obj_set_align(ui_addemployeetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addemployeetxt, _("add employee"));
    lv_obj_set_style_text_color(ui_addemployeetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_addemployeetxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_addemployeetxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addemployeekey = lv_keyboard_create(ui_addemployee);
    lv_obj_set_height(ui_addemployeekey, 141);
    lv_obj_set_width(ui_addemployeekey, lv_pct(100));
    lv_obj_set_x(ui_addemployeekey, 0);
    lv_obj_set_y(ui_addemployeekey, 64);
    lv_obj_set_align(ui_addemployeekey, LV_ALIGN_CENTER);

    ui_addemployeename = lv_textarea_create(ui_addemployee);
    lv_obj_set_width(ui_addemployeename, 238);
    lv_obj_set_height(ui_addemployeename, 58);
    lv_obj_set_x(ui_addemployeename, 0);
    lv_obj_set_y(ui_addemployeename, -63);
    lv_obj_set_align(ui_addemployeename, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_addemployeename, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_addemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_addemployeename, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_addemployeename, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_addemployeename, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_addemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainpanel2 = lv_obj_create(ui_addemployee);
    lv_obj_set_width(ui_mainpanel2, lv_pct(100));
    lv_obj_set_height(ui_mainpanel2, lv_pct(100));
    lv_obj_set_align(ui_mainpanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mainpanel2, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_mainpanel2, LV_DIR_VER);
    lv_obj_set_style_radius(ui_mainpanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainpanel2, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainpanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp2 = lv_obj_create(ui_mainpanel2);
    lv_obj_set_width(ui_fingertemp2, 251);
    lv_obj_set_height(ui_fingertemp2, 149);
    lv_obj_set_x(ui_fingertemp2, 0);
    lv_obj_set_y(ui_fingertemp2, -14);
    lv_obj_set_align(ui_fingertemp2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fingertemp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image100 = lv_image_create(ui_fingertemp2);
    lv_image_set_src(ui_Image100, &ui_img_222311654);
    lv_obj_set_width(ui_Image100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image100, 0);
    lv_obj_set_y(ui_Image100, -25);
    lv_obj_set_align(ui_Image100, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image100, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image100, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt3 = lv_label_create(ui_fingertemp2);
    lv_obj_set_width(ui_plustxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt3, 1);
    lv_obj_set_y(ui_plustxt3, 31);
    lv_obj_set_align(ui_plustxt3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt3, _("please place your finger"));
    lv_obj_set_style_text_color(ui_plustxt3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtomenu4 = lv_button_create(ui_mainpanel2);
    lv_obj_set_width(ui_backtomenu4, 50);
    lv_obj_set_height(ui_backtomenu4, 38);
    lv_obj_set_x(ui_backtomenu4, -202);
    lv_obj_set_y(ui_backtomenu4, -114);
    lv_obj_set_align(ui_backtomenu4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu4, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu4, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg4 = lv_image_create(ui_backtomenu4);
    lv_image_set_src(ui_backimg4, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fingertemp = lv_obj_create(ui_mainpanel2);
    lv_obj_set_width(ui_fingertemp, 251);
    lv_obj_set_height(ui_fingertemp, 149);
    lv_obj_set_x(ui_fingertemp, 0);
    lv_obj_set_y(ui_fingertemp, -14);
    lv_obj_set_align(ui_fingertemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image300 = lv_image_create(ui_fingertemp);
    lv_image_set_src(ui_Image300, &ui_img_565519698);
    lv_obj_set_width(ui_Image300, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image300, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image300, 0);
    lv_obj_set_y(ui_Image300, -25);
    lv_obj_set_align(ui_Image300, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image300, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image300, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt4 = lv_label_create(ui_fingertemp);
    lv_obj_set_width(ui_plustxt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt4, 1);
    lv_obj_set_y(ui_plustxt4, 31);
    lv_obj_set_align(ui_plustxt4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt4, _("Done successfully"));
    lv_obj_set_style_text_color(ui_plustxt4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp3 = lv_obj_create(ui_mainpanel2);
    lv_obj_set_width(ui_fingertemp3, 251);
    lv_obj_set_height(ui_fingertemp3, 149);
    lv_obj_set_x(ui_fingertemp3, 0);
    lv_obj_set_y(ui_fingertemp3, -14);
    lv_obj_set_align(ui_fingertemp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp3, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image200 = lv_image_create(ui_fingertemp3);
    lv_image_set_src(ui_Image200, &ui_img_881979347);
    lv_obj_set_width(ui_Image200, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image200, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image200, 0);
    lv_obj_set_y(ui_Image200, -25);
    lv_obj_set_align(ui_Image200, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image200, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image200, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt5 = lv_label_create(ui_fingertemp3);
    lv_obj_set_width(ui_plustxt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt5, 1);
    lv_obj_set_y(ui_plustxt5, 31);
    lv_obj_set_align(ui_plustxt5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt5, _("fingerprint used or error"));
    lv_obj_set_style_text_color(ui_plustxt5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp4 = lv_obj_create(ui_mainpanel2);
    lv_obj_set_width(ui_fingertemp4, 251);
    lv_obj_set_height(ui_fingertemp4, 149);
    lv_obj_set_x(ui_fingertemp4, 0);
    lv_obj_set_y(ui_fingertemp4, -14);
    lv_obj_set_align(ui_fingertemp4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp4, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp4, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23113 = lv_image_create(ui_fingertemp4);
    lv_image_set_src(ui_Image23113, &ui_img_222311654);
    lv_obj_set_width(ui_Image23113, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23113, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23113, 0);
    lv_obj_set_y(ui_Image23113, -25);
    lv_obj_set_align(ui_Image23113, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23113, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23113, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt6 = lv_label_create(ui_fingertemp4);
    lv_obj_set_width(ui_plustxt6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt6, 1);
    lv_obj_set_y(ui_plustxt6, 31);
    lv_obj_set_align(ui_plustxt6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt6, _("place your finger again"));
    lv_obj_set_style_text_color(ui_plustxt6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp5 = lv_obj_create(ui_addemployee);
    lv_obj_set_width(ui_fingertemp5, 251);
    lv_obj_set_height(ui_fingertemp5, 149);
    lv_obj_set_x(ui_fingertemp5, 0);
    lv_obj_set_y(ui_fingertemp5, -14);
    lv_obj_set_align(ui_fingertemp5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp5, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp5, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2000 = lv_image_create(ui_fingertemp5);
    lv_image_set_src(ui_Image2000, &ui_img_670821478);
    lv_obj_set_width(ui_Image2000, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2000, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2000, 0);
    lv_obj_set_y(ui_Image2000, -25);
    lv_obj_set_align(ui_Image2000, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2000, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2000, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt7 = lv_label_create(ui_fingertemp5);
    lv_obj_set_width(ui_plustxt7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt7, 1);
    lv_obj_set_y(ui_plustxt7, 31);
    lv_obj_set_align(ui_plustxt7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt7, _("Done successfully"));
    lv_obj_set_style_text_color(ui_plustxt7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp6 = lv_obj_create(ui_addemployee);
    lv_obj_set_width(ui_fingertemp6, 251);
    lv_obj_set_height(ui_fingertemp6, 149);
    lv_obj_set_x(ui_fingertemp6, 0);
    lv_obj_set_y(ui_fingertemp6, -14);
    lv_obj_set_align(ui_fingertemp6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp6, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp6, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image110000 = lv_image_create(ui_fingertemp6);
    lv_image_set_src(ui_Image110000, &ui_img_1872894617);
    lv_obj_set_width(ui_Image110000, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image110000, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image110000, 0);
    lv_obj_set_y(ui_Image110000, -25);
    lv_obj_set_align(ui_Image110000, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image110000, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image110000, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt8 = lv_label_create(ui_fingertemp6);
    lv_obj_set_width(ui_plustxt8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt8, 1);
    lv_obj_set_y(ui_plustxt8, 31);
    lv_obj_set_align(ui_plustxt8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt8, _("error"));
    lv_obj_set_style_text_color(ui_plustxt8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backtomenu3, ui_event_backtomenu3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_addemployeekey, ui_addemployeename);
    lv_obj_add_event_cb(ui_backtomenu4, ui_event_backtomenu4, LV_EVENT_ALL, NULL);
    uic_addemployee = ui_addemployee;
    uic_addemployeeaction = ui_addemployeeaction;
    uic_plustxt = ui_plustxt;
    uic_addemployeetxt = ui_addemployeetxt;
    uic_addemployeekey = ui_addemployeekey;
    uic_addemployeename = ui_addemployeename;
    uic_mainpanel2 = ui_mainpanel2;
    uic_fingertemp2 = ui_fingertemp2;
    uic_Image100 = ui_Image100;
    uic_plustxt3 = ui_plustxt3;
    uic_fingertemp = ui_fingertemp;
    uic_Image300 = ui_Image300;
    uic_plustxt4 = ui_plustxt4;
    uic_fingertemp3 = ui_fingertemp3;
    uic_plustxt5 = ui_plustxt5;
    uic_fingertemp4 = ui_fingertemp4;
    uic_plustxt6 = ui_plustxt6;
    uic_plustxt7 = ui_plustxt7;
    uic_Image110000 = ui_Image110000;
    uic_plustxt8 = ui_plustxt8;

}

void ui_addemployee_screen_destroy(void)
{
    if(ui_addemployee) lv_obj_del(ui_addemployee);

    // NULL screen variables
    uic_addemployee = NULL;
    ui_addemployee = NULL;
    ui_backtomenu3 = NULL;
    ui_backimg3 = NULL;
    uic_addemployeeaction = NULL;
    ui_addemployeeaction = NULL;
    uic_plustxt = NULL;
    ui_plustxt = NULL;
    uic_addemployeetxt = NULL;
    ui_addemployeetxt = NULL;
    uic_addemployeekey = NULL;
    ui_addemployeekey = NULL;
    uic_addemployeename = NULL;
    ui_addemployeename = NULL;
    uic_mainpanel2 = NULL;
    ui_mainpanel2 = NULL;
    uic_fingertemp2 = NULL;
    ui_fingertemp2 = NULL;
    uic_Image100 = NULL;
    ui_Image100 = NULL;
    uic_plustxt3 = NULL;
    ui_plustxt3 = NULL;
    ui_backtomenu4 = NULL;
    ui_backimg4 = NULL;
    uic_fingertemp = NULL;
    ui_fingertemp = NULL;
    uic_Image300 = NULL;
    ui_Image300 = NULL;
    uic_plustxt4 = NULL;
    ui_plustxt4 = NULL;
    uic_fingertemp3 = NULL;
    ui_fingertemp3 = NULL;
    ui_Image200 = NULL;
    uic_plustxt5 = NULL;
    ui_plustxt5 = NULL;
    uic_fingertemp4 = NULL;
    ui_fingertemp4 = NULL;
    ui_Image23113 = NULL;
    uic_plustxt6 = NULL;
    ui_plustxt6 = NULL;
    ui_fingertemp5 = NULL;
    ui_Image2000 = NULL;
    uic_plustxt7 = NULL;
    ui_plustxt7 = NULL;
    ui_fingertemp6 = NULL;
    uic_Image110000 = NULL;
    ui_Image110000 = NULL;
    uic_plustxt8 = NULL;
    ui_plustxt8 = NULL;

}

void ui_addemployee_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_addemployeetxt) && lv_obj_is_valid(ui_addemployeetxt)) lv_label_set_text(ui_addemployeetxt, _("add employee"));
    if((ui_plustxt3) && lv_obj_is_valid(ui_plustxt3)) lv_label_set_text(ui_plustxt3, _("please place your finger"));
    if((ui_plustxt4) && lv_obj_is_valid(ui_plustxt4)) lv_label_set_text(ui_plustxt4, _("Done successfully"));
    if((ui_plustxt5) && lv_obj_is_valid(ui_plustxt5)) lv_label_set_text(ui_plustxt5, _("fingerprint used or error"));
    if((ui_plustxt6) && lv_obj_is_valid(ui_plustxt6)) lv_label_set_text(ui_plustxt6, _("place your finger again"));
    if((ui_plustxt7) && lv_obj_is_valid(ui_plustxt7)) lv_label_set_text(ui_plustxt7, _("Done successfully"));
    if((ui_plustxt8) && lv_obj_is_valid(ui_plustxt8)) lv_label_set_text(ui_plustxt8, _("error"));

}
