// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_ADDEMPLOYEE_H
#define UI_ADDEMPLOYEE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_addemployee
extern void ui_addemployee_screen_init(void);
extern void ui_addemployee_screen_destroy(void);
extern void ui_addemployee_screen_relocalize(void);
extern lv_obj_t * ui_addemployee;
extern void ui_event_backtomenu3(lv_event_t * e);
extern lv_obj_t * ui_backtomenu3;
extern lv_obj_t * ui_backimg3;
extern lv_obj_t * ui_addemployeeaction;
extern lv_obj_t * ui_plustxt;
extern lv_obj_t * ui_addemployeetxt;
extern lv_obj_t * ui_addemployeekey;
extern lv_obj_t * ui_addemployeename;
extern lv_obj_t * ui_mainpanel2;
extern lv_obj_t * ui_fingertemp2;
extern lv_obj_t * ui_Image100;
extern lv_obj_t * ui_plustxt3;
extern void ui_event_backtomenu4(lv_event_t * e);
extern lv_obj_t * ui_backtomenu4;
extern lv_obj_t * ui_backimg4;
extern lv_obj_t * ui_fingertemp;
extern lv_obj_t * ui_Image300;
extern lv_obj_t * ui_plustxt4;
extern lv_obj_t * ui_fingertemp3;
extern lv_obj_t * ui_Image200;
extern lv_obj_t * ui_plustxt5;
extern lv_obj_t * ui_fingertemp4;
extern lv_obj_t * ui_Image23113;
extern lv_obj_t * ui_plustxt6;
extern lv_obj_t * ui_fingertemp5;
extern lv_obj_t * ui_Image2000;
extern lv_obj_t * ui_plustxt7;
extern lv_obj_t * ui_fingertemp6;
extern lv_obj_t * ui_Image110000;
extern lv_obj_t * ui_plustxt8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_addemployee;
extern lv_obj_t * uic_addemployeeaction;
extern lv_obj_t * uic_plustxt;
extern lv_obj_t * uic_addemployeetxt;
extern lv_obj_t * uic_addemployeekey;
extern lv_obj_t * uic_addemployeename;
extern lv_obj_t * uic_mainpanel2;
extern lv_obj_t * uic_fingertemp2;
extern lv_obj_t * uic_Image100;
extern lv_obj_t * uic_plustxt3;
extern lv_obj_t * uic_fingertemp;
extern lv_obj_t * uic_Image300;
extern lv_obj_t * uic_plustxt4;
extern lv_obj_t * uic_fingertemp3;
extern lv_obj_t * uic_plustxt5;
extern lv_obj_t * uic_fingertemp4;
extern lv_obj_t * uic_plustxt6;
extern lv_obj_t * uic_plustxt7;
extern lv_obj_t * uic_Image110000;
extern lv_obj_t * uic_plustxt8;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

