// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label22;
lv_obj_t * uic_correct;
lv_obj_t * uic_Label1;
lv_obj_t * uic_wrong;
lv_obj_t * uic_loadingbar2;
lv_obj_t * uic_loading2;
lv_obj_t * uic_loadingoverlay2;
lv_obj_t * uic_selectednetwork;
lv_obj_t * uic_btntxt;
lv_obj_t * uic_connectbtn;
lv_obj_t * uic_passwordtxt;
lv_obj_t * uic_connectwifi;
lv_obj_t * ui_connectwifi = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_passwordtxt = NULL;
lv_obj_t * ui_connectbtn = NULL;
lv_obj_t * ui_btntxt = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_selectednetwork = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_loadingoverlay2 = NULL;
lv_obj_t * ui_loading2 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_loadingbar2 = NULL;
lv_obj_t * ui_wrong = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_correct = NULL;
lv_obj_t * ui_Label22 = NULL;
// event funtions
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiset, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiset_screen_init);
    }
}

// build funtions

void ui_connectwifi_screen_init(void)
{
    ui_connectwifi = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_connectwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connectwifi, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_connectwifi);
    lv_obj_set_height(ui_Keyboard2, 160);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_x(ui_Keyboard2, 1);
    lv_obj_set_y(ui_Keyboard2, 0);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_radius(ui_Keyboard2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_button_create(ui_connectwifi);
    lv_obj_set_width(ui_Button12, 50);
    lv_obj_set_height(ui_Button12, 38);
    lv_obj_set_x(ui_Button12, -203);
    lv_obj_set_y(ui_Button12, -113);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_image_create(ui_Button12);
    lv_image_set_src(ui_Image21, &ui_img_1385604958);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_passwordtxt = lv_textarea_create(ui_connectwifi);
    lv_obj_set_width(ui_passwordtxt, 290);
    lv_obj_set_height(ui_passwordtxt, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_passwordtxt, 0);
    lv_obj_set_y(ui_passwordtxt, -59);
    lv_obj_set_align(ui_passwordtxt, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordtxt, "password");
    lv_textarea_set_one_line(ui_passwordtxt, true);
    lv_textarea_set_password_mode(ui_passwordtxt, true);
    lv_obj_remove_flag(ui_passwordtxt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_passwordtxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_passwordtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_passwordtxt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_passwordtxt, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passwordtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_passwordtxt, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_passwordtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_passwordtxt, 4, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_passwordtxt, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passwordtxt, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_connectbtn = lv_button_create(ui_connectwifi);
    lv_obj_set_width(ui_connectbtn, 81);
    lv_obj_set_height(ui_connectbtn, 31);
    lv_obj_set_x(ui_connectbtn, 196);
    lv_obj_set_y(ui_connectbtn, -118);
    lv_obj_set_align(ui_connectbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_connectbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connectbtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connectbtn, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connectbtn, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connectbtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_connectbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_connectbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btntxt = lv_label_create(ui_connectwifi);
    lv_obj_set_width(ui_btntxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btntxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_btntxt, 196);
    lv_obj_set_y(ui_btntxt, -118);
    lv_obj_set_align(ui_btntxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btntxt, "connect");
    lv_obj_set_style_text_color(ui_btntxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btntxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btntxt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_connectwifi);
    lv_obj_set_width(ui_Panel1, 309);
    lv_obj_set_height(ui_Panel1, 27);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, -106);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_selectednetwork = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_selectednetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selectednetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectednetwork, 103);
    lv_obj_set_y(ui_selectednetwork, 2);
    lv_obj_set_align(ui_selectednetwork, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_selectednetwork, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_selectednetwork, "my_netowrk");
    lv_obj_set_style_text_color(ui_selectednetwork, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_selectednetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_selectednetwork, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_Image23, &ui_img_1799210772);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, -46);
    lv_obj_set_y(ui_Image23, 1);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadingoverlay2 = lv_obj_create(ui_connectwifi);
    lv_obj_set_width(ui_loadingoverlay2, lv_pct(103));
    lv_obj_set_height(ui_loadingoverlay2, lv_pct(110));
    lv_obj_set_x(ui_loadingoverlay2, -4);
    lv_obj_set_y(ui_loadingoverlay2, 4);
    lv_obj_set_align(ui_loadingoverlay2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadingoverlay2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_loadingoverlay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loadingoverlay2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingoverlay2, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loadingoverlay2, lv_color_hex(0x4A5670), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loadingoverlay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loading2 = lv_obj_create(ui_connectwifi);
    lv_obj_set_width(ui_loading2, 200);
    lv_obj_set_height(ui_loading2, 100);
    lv_obj_set_x(ui_loading2, 2);
    lv_obj_set_y(ui_loading2, 0);
    lv_obj_set_align(ui_loading2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_loading2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_loading2, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loading2, lv_color_hex(0x232A3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loading2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loading2, lv_color_hex(0x2A3C58), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loading2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_loading2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 7);
    lv_obj_set_y(ui_Label20, -17);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "connecting...");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadingbar2 = lv_bar_create(ui_loading2);
    lv_bar_set_value(ui_loadingbar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_loadingbar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_loadingbar2, 150);
    lv_obj_set_height(ui_loadingbar2, 10);
    lv_obj_set_align(ui_loadingbar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_loadingbar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loadingbar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loadingbar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_loadingbar2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_loadingbar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_loadingbar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_loadingbar2,
                                                                                                  lv_obj_get_style_pad_right(ui_loadingbar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_wrong = lv_obj_create(ui_connectwifi);
    lv_obj_set_width(ui_wrong, 128);
    lv_obj_set_height(ui_wrong, 34);
    lv_obj_set_x(ui_wrong, 0);
    lv_obj_set_y(ui_wrong, -105);
    lv_obj_set_align(ui_wrong, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wrong, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wrong, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wrong, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wrong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wrong, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wrong, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_wrong);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, _("wrong password"));
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_correct = lv_obj_create(ui_connectwifi);
    lv_obj_set_width(ui_correct, 128);
    lv_obj_set_height(ui_correct, 34);
    lv_obj_set_x(ui_correct, 0);
    lv_obj_set_y(ui_correct, -105);
    lv_obj_set_align(ui_correct, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_correct, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_correct, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_correct, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_correct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_correct, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_correct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_correct);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, _("connected..."));
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard2, ui_passwordtxt);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    uic_connectwifi = ui_connectwifi;
    uic_passwordtxt = ui_passwordtxt;
    uic_connectbtn = ui_connectbtn;
    uic_btntxt = ui_btntxt;
    uic_selectednetwork = ui_selectednetwork;
    uic_loadingoverlay2 = ui_loadingoverlay2;
    uic_loading2 = ui_loading2;
    uic_loadingbar2 = ui_loadingbar2;
    uic_wrong = ui_wrong;
    uic_Label1 = ui_Label1;
    uic_correct = ui_correct;
    uic_Label22 = ui_Label22;

}

void ui_connectwifi_screen_destroy(void)
{
    if(ui_connectwifi) lv_obj_del(ui_connectwifi);

    // NULL screen variables
    uic_connectwifi = NULL;
    ui_connectwifi = NULL;
    ui_Keyboard2 = NULL;
    ui_Button12 = NULL;
    ui_Image21 = NULL;
    uic_passwordtxt = NULL;
    ui_passwordtxt = NULL;
    uic_connectbtn = NULL;
    ui_connectbtn = NULL;
    uic_btntxt = NULL;
    ui_btntxt = NULL;
    ui_Panel1 = NULL;
    uic_selectednetwork = NULL;
    ui_selectednetwork = NULL;
    ui_Image23 = NULL;
    uic_loadingoverlay2 = NULL;
    ui_loadingoverlay2 = NULL;
    uic_loading2 = NULL;
    ui_loading2 = NULL;
    ui_Label20 = NULL;
    uic_loadingbar2 = NULL;
    ui_loadingbar2 = NULL;
    uic_wrong = NULL;
    ui_wrong = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    uic_correct = NULL;
    ui_correct = NULL;
    uic_Label22 = NULL;
    ui_Label22 = NULL;

}

void ui_connectwifi_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_Label1) && lv_obj_is_valid(ui_Label1)) lv_label_set_text(ui_Label1, _("wrong password"));
    if((ui_Label22) && lv_obj_is_valid(ui_Label22)) lv_label_set_text(ui_Label22, _("connected..."));

}
