// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CONNECTWIFI_H
#define UI_CONNECTWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_connectwifi
extern void ui_connectwifi_screen_init(void);
extern void ui_connectwifi_screen_destroy(void);
extern void ui_connectwifi_screen_relocalize(void);
extern lv_obj_t * ui_connectwifi;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_passwordtxt;
extern lv_obj_t * ui_connectbtn;
extern lv_obj_t * ui_btntxt;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_selectednetwork;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_loadingoverlay2;
extern lv_obj_t * ui_loading2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_loadingbar2;
extern lv_obj_t * ui_wrong;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_correct;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t * uic_connectwifi;
extern lv_obj_t * uic_passwordtxt;
extern lv_obj_t * uic_connectbtn;
extern lv_obj_t * uic_btntxt;
extern lv_obj_t * uic_selectednetwork;
extern lv_obj_t * uic_loadingoverlay2;
extern lv_obj_t * uic_loading2;
extern lv_obj_t * uic_loadingbar2;
extern lv_obj_t * uic_wrong;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_correct;
extern lv_obj_t * uic_Label22;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

