// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_fingertemp7;
lv_obj_t * uic_okpopup2;
lv_obj_t * uic_changepassbtn;
lv_obj_t * uic_changpassbox;
lv_obj_t * uic_changepasskey;
lv_obj_t * uic_changepassscreen;
lv_obj_t * ui_changepassscreen = NULL;
lv_obj_t * ui_backtomenu5 = NULL;
lv_obj_t * ui_backimg5 = NULL;
lv_obj_t * ui_changepasskey = NULL;
lv_obj_t * ui_changpassbox = NULL;
lv_obj_t * ui_changepassbtn = NULL;
lv_obj_t * ui_backimg7 = NULL;
lv_obj_t * ui_okpopup2 = NULL;
lv_obj_t * ui_Image20000 = NULL;
lv_obj_t * ui_plustxt16 = NULL;
lv_obj_t * ui_fingertemp7 = NULL;
lv_obj_t * ui_Image30000 = NULL;
lv_obj_t * ui_plustxt17 = NULL;
// event funtions
void ui_event_backtomenu5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_employee_screen_init);
    }
}

// build funtions

void ui_changepassscreen_screen_init(void)
{
    ui_changepassscreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_changepassscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changepassscreen, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changepassscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtomenu5 = lv_button_create(ui_changepassscreen);
    lv_obj_set_width(ui_backtomenu5, 50);
    lv_obj_set_height(ui_backtomenu5, 38);
    lv_obj_set_x(ui_backtomenu5, -202);
    lv_obj_set_y(ui_backtomenu5, -114);
    lv_obj_set_align(ui_backtomenu5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu5, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu5, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg5 = lv_image_create(ui_backtomenu5);
    lv_image_set_src(ui_backimg5, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changepasskey = lv_keyboard_create(ui_changepassscreen);
    lv_keyboard_set_mode(ui_changepasskey, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_height(ui_changepasskey, 141);
    lv_obj_set_width(ui_changepasskey, lv_pct(100));
    lv_obj_set_x(ui_changepasskey, 0);
    lv_obj_set_y(ui_changepasskey, 64);
    lv_obj_set_align(ui_changepasskey, LV_ALIGN_CENTER);

    ui_changpassbox = lv_textarea_create(ui_changepassscreen);
    lv_obj_set_width(ui_changpassbox, 238);
    lv_obj_set_height(ui_changpassbox, 58);
    lv_obj_set_x(ui_changpassbox, 0);
    lv_obj_set_y(ui_changpassbox, -63);
    lv_obj_set_align(ui_changpassbox, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_changpassbox, 4);
    lv_obj_set_style_text_color(ui_changpassbox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_changpassbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_changpassbox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changpassbox, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changpassbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changpassbox, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changpassbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changepassbtn = lv_button_create(ui_changepassscreen);
    lv_obj_set_width(ui_changepassbtn, 50);
    lv_obj_set_height(ui_changepassbtn, 38);
    lv_obj_set_x(ui_changepassbtn, 203);
    lv_obj_set_y(ui_changepassbtn, -113);
    lv_obj_set_align(ui_changepassbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changepassbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changepassbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changepassbtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changepassbtn, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changepassbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changepassbtn, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changepassbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changepassbtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changepassbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changepassbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg7 = lv_image_create(ui_changepassbtn);
    lv_image_set_src(ui_backimg7, &ui_img_1790866911);
    lv_obj_set_width(ui_backimg7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okpopup2 = lv_obj_create(ui_changepassscreen);
    lv_obj_set_width(ui_okpopup2, 251);
    lv_obj_set_height(ui_okpopup2, 149);
    lv_obj_set_x(ui_okpopup2, 0);
    lv_obj_set_y(ui_okpopup2, -14);
    lv_obj_set_align(ui_okpopup2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okpopup2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_okpopup2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_okpopup2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_okpopup2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okpopup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_okpopup2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_okpopup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_okpopup2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_okpopup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_okpopup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20000 = lv_image_create(ui_okpopup2);
    lv_image_set_src(ui_Image20000, &ui_img_670821478);
    lv_obj_set_width(ui_Image20000, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20000, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20000, 0);
    lv_obj_set_y(ui_Image20000, -25);
    lv_obj_set_align(ui_Image20000, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20000, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20000, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt16 = lv_label_create(ui_okpopup2);
    lv_obj_set_width(ui_plustxt16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt16, 1);
    lv_obj_set_y(ui_plustxt16, 31);
    lv_obj_set_align(ui_plustxt16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt16, _("Done successfully"));
    lv_obj_set_style_text_color(ui_plustxt16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt16, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertemp7 = lv_obj_create(ui_changepassscreen);
    lv_obj_set_width(ui_fingertemp7, 251);
    lv_obj_set_height(ui_fingertemp7, 149);
    lv_obj_set_x(ui_fingertemp7, 0);
    lv_obj_set_y(ui_fingertemp7, -14);
    lv_obj_set_align(ui_fingertemp7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fingertemp7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fingertemp7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fingertemp7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fingertemp7, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fingertemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fingertemp7, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fingertemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fingertemp7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fingertemp7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fingertemp7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image30000= lv_image_create(ui_fingertemp7);
    lv_image_set_src(ui_Image30000, &ui_img_1872894617);
    lv_obj_set_width(ui_Image30000, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30000, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image30000, 0);
    lv_obj_set_y(ui_Image30000, -25);
    lv_obj_set_align(ui_Image30000, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30000, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image30000, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt17 = lv_label_create(ui_fingertemp7);
    lv_obj_set_width(ui_plustxt17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt17, 1);
    lv_obj_set_y(ui_plustxt17, 31);
    lv_obj_set_align(ui_plustxt17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt17, _("error"));
    lv_obj_set_style_text_color(ui_plustxt17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backtomenu5, ui_event_backtomenu5, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_changepasskey, ui_changpassbox);
    uic_changepassscreen = ui_changepassscreen;
    uic_changepasskey = ui_changepasskey;
    uic_changpassbox = ui_changpassbox;
    uic_changepassbtn = ui_changepassbtn;
    uic_okpopup2 = ui_okpopup2;
    uic_fingertemp7 = ui_fingertemp7;

}

void ui_changepassscreen_screen_destroy(void)
{
    if(ui_changepassscreen) lv_obj_del(ui_changepassscreen);

    // NULL screen variables
    uic_changepassscreen = NULL;
    ui_changepassscreen = NULL;
    ui_backtomenu5 = NULL;
    ui_backimg5 = NULL;
    uic_changepasskey = NULL;
    ui_changepasskey = NULL;
    uic_changpassbox = NULL;
    ui_changpassbox = NULL;
    uic_changepassbtn = NULL;
    ui_changepassbtn = NULL;
    ui_backimg7 = NULL;
    uic_okpopup2 = NULL;
    ui_okpopup2 = NULL;
    ui_Image20000 = NULL;
    ui_plustxt16 = NULL;
    uic_fingertemp7 = NULL;
    ui_fingertemp7 = NULL;
    ui_Image30000 = NULL;
    ui_plustxt17 = NULL;

}

void ui_changepassscreen_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_plustxt16) && lv_obj_is_valid(ui_plustxt16)) lv_label_set_text(ui_plustxt16, _("Done successfully"));
    if((ui_plustxt17) && lv_obj_is_valid(ui_plustxt17)) lv_label_set_text(ui_plustxt17, _("error"));

}
