// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CHANGEPASSSCREEN_H
#define UI_CHANGEPASSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_changepassscreen
extern void ui_changepassscreen_screen_init(void);
extern void ui_changepassscreen_screen_destroy(void);
extern void ui_changepassscreen_screen_relocalize(void);
extern lv_obj_t * ui_changepassscreen;
extern void ui_event_backtomenu5(lv_event_t * e);
extern lv_obj_t * ui_backtomenu5;
extern lv_obj_t * ui_backimg5;
extern lv_obj_t * ui_changepasskey;
extern lv_obj_t * ui_changpassbox;
extern lv_obj_t * ui_changepassbtn;
extern lv_obj_t * ui_backimg7;
extern lv_obj_t * ui_okpopup2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_plustxt16;
extern lv_obj_t * ui_fingertemp7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_plustxt17;
// CUSTOM VARIABLES
extern lv_obj_t * uic_changepassscreen;
extern lv_obj_t * uic_changepasskey;
extern lv_obj_t * uic_changpassbox;
extern lv_obj_t * uic_changepassbtn;
extern lv_obj_t * uic_okpopup2;
extern lv_obj_t * uic_fingertemp7;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

