// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_DATE_H
#define UI_DATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_date
extern void ui_date_screen_init(void);
extern void ui_date_screen_destroy(void);
extern void ui_date_screen_relocalize(void);
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_timemin;
extern lv_obj_t * ui_timehour;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_ampm;
extern lv_obj_t * ui_savetime;
extern lv_obj_t * ui_savetxt2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_month;
extern lv_obj_t * ui_years;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_timemin;
extern lv_obj_t * uic_timehour;
extern lv_obj_t * uic_ampm;
extern lv_obj_t * uic_savetime;
extern lv_obj_t * uic_savetxt2;
extern lv_obj_t * uic_Label4;
extern lv_obj_t * uic_Label6;
extern lv_obj_t * uic_day;
extern lv_obj_t * uic_month;
extern lv_obj_t * uic_years;
extern lv_obj_t * uic_Label9;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

