// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label9;
lv_obj_t * uic_years;
lv_obj_t * uic_month;
lv_obj_t * uic_day;
lv_obj_t * uic_Label6;
lv_obj_t * uic_Label4;
lv_obj_t * uic_savetxt2;
lv_obj_t * uic_savetime;
lv_obj_t * uic_ampm;
lv_obj_t * uic_timehour;
lv_obj_t * uic_timemin;
lv_obj_t * uic_date;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_timemin = NULL;
lv_obj_t * ui_timehour = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Image31 = NULL;
lv_obj_t * ui_ampm = NULL;
lv_obj_t * ui_savetime = NULL;
lv_obj_t * ui_savetxt2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_month = NULL;
lv_obj_t * ui_years = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_date_screen_init(void)
{
    ui_date = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_date, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_date, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timemin = lv_roller_create(ui_date);
    lv_roller_set_options(ui_timemin,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_timemin, 59);
    lv_obj_set_height(ui_timemin, 73);
    lv_obj_set_x(ui_timemin, 152);
    lv_obj_set_y(ui_timemin, -35);
    lv_obj_set_align(ui_timemin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_timemin, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timemin, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timemin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timemin, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timemin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timemin, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timemin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_timehour = lv_roller_create(ui_date);
    lv_roller_set_options(ui_timehour, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_timehour, 57);
    lv_obj_set_height(ui_timehour, 73);
    lv_obj_set_x(ui_timehour, 82);
    lv_obj_set_y(ui_timehour, -35);
    lv_obj_set_align(ui_timehour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_timehour, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timehour, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timehour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timehour, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timehour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timehour, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timehour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 120);
    lv_obj_set_y(ui_Label3, -35);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, ":");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_date);
    lv_obj_set_width(ui_Button6, 50);
    lv_obj_set_height(ui_Button6, 38);
    lv_obj_set_x(ui_Button6, -203);
    lv_obj_set_y(ui_Button6, -113);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_image_create(ui_Button6);
    lv_image_set_src(ui_Image31, &ui_img_1385604958);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ampm = lv_roller_create(ui_date);
    lv_roller_set_options(ui_ampm, "AM\nPM", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_ampm, 37);
    lv_obj_set_height(ui_ampm, 35);
    lv_obj_set_x(ui_ampm, 192);
    lv_obj_set_y(ui_ampm, -21);
    lv_obj_set_align(ui_ampm, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ampm, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ampm, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ampm, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ampm, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ampm, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_savetime = lv_button_create(ui_date);
    lv_obj_set_width(ui_savetime, 290);
    lv_obj_set_height(ui_savetime, 53);
    lv_obj_set_x(ui_savetime, 0);
    lv_obj_set_y(ui_savetime, 79);
    lv_obj_set_align(ui_savetime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_savetime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_savetime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_savetime, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_savetime, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_savetime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_savetime, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_savetime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_savetime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_savetime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_savetime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_savetime, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_savetime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_savetime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_savetime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_savetxt2 = lv_label_create(ui_savetime);
    lv_obj_set_width(ui_savetxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_savetxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_savetxt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_savetxt2, _("save"));
    lv_obj_set_style_text_color(ui_savetxt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_savetxt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_savetxt2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 119);
    lv_obj_set_y(ui_Label4, -68);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, _("time"));
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -117);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, _("time"));
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_roller_create(ui_date);
    lv_roller_set_options(ui_day,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_day, 40);
    lv_obj_set_height(ui_day, 73);
    lv_obj_set_x(ui_day, -36);
    lv_obj_set_y(ui_day, -34);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_day, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_day, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_day, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -78);
    lv_obj_set_y(ui_Label7, -35);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "/");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_roller_create(ui_date);
    lv_roller_set_options(ui_month, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_month, 57);
    lv_obj_set_height(ui_month, 73);
    lv_obj_set_x(ui_month, -118);
    lv_obj_set_y(ui_month, -35);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_month, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_month, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_month, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_month, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_month, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_years = lv_roller_create(ui_date);
    lv_roller_set_options(ui_years,
                          "2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035\n2036\n2037\n2038\n2039\n2040\n2041\n2042\n2043\n2044\n2045\n2046\n2047\n2048\n2049\n2050\n2051\n2052\n2053\n2054\n2055\n2056\n2057\n2058\n2059\n2060",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_years, 62);
    lv_obj_set_height(ui_years, 73);
    lv_obj_set_x(ui_years, -195);
    lv_obj_set_y(ui_years, -35);
    lv_obj_set_align(ui_years, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_years, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_years, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_years, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_years, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_years, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_years, lv_color_hex(0x0B0D12), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_years, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -153);
    lv_obj_set_y(ui_Label8, -35);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "/");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_date);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -128);
    lv_obj_set_y(ui_Label9, -68);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, _("date"));
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    uic_date = ui_date;
    uic_timemin = ui_timemin;
    uic_timehour = ui_timehour;
    uic_ampm = ui_ampm;
    uic_savetime = ui_savetime;
    uic_savetxt2 = ui_savetxt2;
    uic_Label4 = ui_Label4;
    uic_Label6 = ui_Label6;
    uic_day = ui_day;
    uic_month = ui_month;
    uic_years = ui_years;
    uic_Label9 = ui_Label9;

}

void ui_date_screen_destroy(void)
{
    if(ui_date) lv_obj_del(ui_date);

    // NULL screen variables
    uic_date = NULL;
    ui_date = NULL;
    uic_timemin = NULL;
    ui_timemin = NULL;
    uic_timehour = NULL;
    ui_timehour = NULL;
    ui_Label3 = NULL;
    ui_Button6 = NULL;
    ui_Image31 = NULL;
    uic_ampm = NULL;
    ui_ampm = NULL;
    uic_savetime = NULL;
    ui_savetime = NULL;
    uic_savetxt2 = NULL;
    ui_savetxt2 = NULL;
    uic_Label4 = NULL;
    ui_Label4 = NULL;
    uic_Label6 = NULL;
    ui_Label6 = NULL;
    uic_day = NULL;
    ui_day = NULL;
    ui_Label7 = NULL;
    uic_month = NULL;
    ui_month = NULL;
    uic_years = NULL;
    ui_years = NULL;
    ui_Label8 = NULL;
    uic_Label9 = NULL;
    ui_Label9 = NULL;

}

void ui_date_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_savetxt2) && lv_obj_is_valid(ui_savetxt2)) lv_label_set_text(ui_savetxt2, _("save"));
    if((ui_Label4) && lv_obj_is_valid(ui_Label4)) lv_label_set_text(ui_Label4, _("time"));
    if((ui_Label6) && lv_obj_is_valid(ui_Label6)) lv_label_set_text(ui_Label6, _("time"));
    if((ui_Label9) && lv_obj_is_valid(ui_Label9)) lv_label_set_text(ui_Label9, _("date"));

}
