// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_deletbtn2ok;
lv_obj_t * uic_deletbtn2no;
lv_obj_t * uic_popup20;
lv_obj_t * uic_plustxt2;
lv_obj_t * uic_gotoadd;
lv_obj_t * uic_employeetxt;
lv_obj_t * uic_backimg;
lv_obj_t * uic_backtomenu;
lv_obj_t * uic_idtxt;
lv_obj_t * uic_deletimage;
lv_obj_t * uic_deletbtn;
lv_obj_t * uic_editimage;
lv_obj_t * uic_editbtn;
lv_obj_t * uic_employeename;
lv_obj_t * uic_txtid;
lv_obj_t * uic_employeetemple;
lv_obj_t * uic_mainemployee;
lv_obj_t * uic_employee;
lv_obj_t * ui_employee = NULL;
lv_obj_t * ui_mainpanel = NULL;
lv_obj_t * ui_mainemployee = NULL;
lv_obj_t * ui_employeetemple = NULL;
lv_obj_t * ui_txtid = NULL;
lv_obj_t * ui_employeename = NULL;
lv_obj_t * ui_editbtn = NULL;
lv_obj_t * ui_editimage = NULL;
lv_obj_t * ui_deletbtn = NULL;
lv_obj_t * ui_deletimage = NULL;
lv_obj_t * ui_idtxt = NULL;
lv_obj_t * ui_backtomenu = NULL;
lv_obj_t * ui_backimg = NULL;
lv_obj_t * ui_employeetxt = NULL;
lv_obj_t * ui_gotoadd = NULL;
lv_obj_t * ui_plustxt2 = NULL;
lv_obj_t * ui_popup20 = NULL;
lv_obj_t * ui_plustxt9 = NULL;
lv_obj_t * ui_deletbtn2no = NULL;
lv_obj_t * ui_plustxt10 = NULL;
lv_obj_t * ui_deletbtn2ok = NULL;
lv_obj_t * ui_plustxt11 = NULL;
// event funtions
void ui_event_gotoadd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addemployee, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_addemployee_screen_init);
    }
}

// build funtions

void ui_employee_screen_init(void)
{
    ui_employee = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_employee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_employee, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_employee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainpanel = lv_obj_create(ui_employee);
    lv_obj_set_height(ui_mainpanel, 225);
    lv_obj_set_width(ui_mainpanel, lv_pct(100));
    lv_obj_set_x(ui_mainpanel, -2);
    lv_obj_set_y(ui_mainpanel, 46);
    lv_obj_remove_flag(ui_mainpanel, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_mainpanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_mainpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainpanel, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainemployee = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_mainemployee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainemployee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainemployee, -143);
    lv_obj_set_y(ui_mainemployee, -83);
    lv_obj_set_align(ui_mainemployee, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainemployee, _("employee name"));
    lv_obj_set_style_text_color(ui_mainemployee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainemployee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainemployee, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetemple = lv_obj_create(ui_mainpanel);
    lv_obj_set_width(ui_employeetemple, 464);
    lv_obj_set_height(ui_employeetemple, 58);
    lv_obj_set_x(ui_employeetemple, 0);
    lv_obj_set_y(ui_employeetemple, -36);
    lv_obj_set_align(ui_employeetemple, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_employeetemple, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_employeetemple, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_employeetemple, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_employeetemple, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_employeetemple, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_employeetemple, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_employeetemple, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_employeetemple, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_employeetemple, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtid = lv_label_create(ui_employeetemple);
    lv_obj_set_width(ui_txtid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtid, 0);
    lv_obj_set_y(ui_txtid, 2);
    lv_obj_set_align(ui_txtid, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_txtid, "100");
    lv_obj_set_style_text_color(ui_txtid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtid, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeename = lv_label_create(ui_employeetemple);
    lv_obj_set_width(ui_employeename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeename, -4);
    lv_obj_set_y(ui_employeename, 3);
    lv_label_set_text(ui_employeename, "employee name");
    lv_obj_set_style_text_color(ui_employeename, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeename, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editbtn = lv_button_create(ui_employeetemple);
    lv_obj_set_width(ui_editbtn, 39);
    lv_obj_set_height(ui_editbtn, 38);
    lv_obj_set_x(ui_editbtn, 58);
    lv_obj_set_y(ui_editbtn, -1);
    lv_obj_set_align(ui_editbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_editbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_editbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_editbtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_editbtn, lv_color_hex(0x27EA39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_editbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_editbtn, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_editbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_editbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_editbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_editbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editimage = lv_image_create(ui_editbtn);
    lv_image_set_src(ui_editimage, &ui_img_1790866911);
    lv_obj_set_width(ui_editimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_editimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_editimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_editimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_editimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_deletbtn = lv_button_create(ui_employeetemple);
    lv_obj_set_width(ui_deletbtn, 39);
    lv_obj_set_height(ui_deletbtn, 38);
    lv_obj_set_x(ui_deletbtn, 112);
    lv_obj_set_y(ui_deletbtn, -1);
    lv_obj_set_align(ui_deletbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_deletbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_deletbtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deletbtn, lv_color_hex(0xEA2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deletbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deletbtn, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deletbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deletbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_deletbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_deletbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletimage = lv_image_create(ui_deletbtn);
    lv_image_set_src(ui_deletimage, &ui_img_1077457577);
    lv_obj_set_width(ui_deletimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deletimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_deletimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_deletimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_idtxt = lv_label_create(ui_mainpanel);
    lv_obj_set_width(ui_idtxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_idtxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_idtxt, 204);
    lv_obj_set_y(ui_idtxt, -83);
    lv_obj_set_align(ui_idtxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_idtxt, _("id"));
    lv_obj_set_style_text_color(ui_idtxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_idtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_idtxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtomenu = lv_button_create(ui_employee);
    lv_obj_set_width(ui_backtomenu, 50);
    lv_obj_set_height(ui_backtomenu, 38);
    lv_obj_set_x(ui_backtomenu, -202);
    lv_obj_set_y(ui_backtomenu, -114);
    lv_obj_set_align(ui_backtomenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg = lv_image_create(ui_backtomenu);
    lv_image_set_src(ui_backimg, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_employeetxt = lv_label_create(ui_employee);
    lv_obj_set_width(ui_employeetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxt, 0);
    lv_obj_set_y(ui_employeetxt, -119);
    lv_obj_set_align(ui_employeetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_employeetxt, _("employee"));
    lv_obj_set_style_text_color(ui_employeetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gotoadd = lv_button_create(ui_employee);
    lv_obj_set_width(ui_gotoadd, 50);
    lv_obj_set_height(ui_gotoadd, 38);
    lv_obj_set_x(ui_gotoadd, 201);
    lv_obj_set_y(ui_gotoadd, -114);
    lv_obj_set_align(ui_gotoadd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gotoadd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_gotoadd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_gotoadd, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gotoadd, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gotoadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gotoadd, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gotoadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gotoadd, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_gotoadd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_gotoadd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt2 = lv_label_create(ui_gotoadd);
    lv_obj_set_width(ui_plustxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt2, "+");
    lv_obj_set_style_text_color(ui_plustxt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_popup20 = lv_obj_create(ui_employee);
    lv_obj_set_width(ui_popup20, 251);
    lv_obj_set_height(ui_popup20, 149);
    lv_obj_set_x(ui_popup20, 0);
    lv_obj_set_y(ui_popup20, -14);
    lv_obj_set_align(ui_popup20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_popup20, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_popup20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_popup20, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_popup20, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_popup20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_popup20, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_popup20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_popup20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_popup20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_popup20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt9 = lv_label_create(ui_popup20);
    lv_obj_set_width(ui_plustxt9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt9, 0);
    lv_obj_set_y(ui_plustxt9, -21);
    lv_obj_set_align(ui_plustxt9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt9, _("are you sure?"));
    lv_obj_set_style_text_color(ui_plustxt9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletbtn2no = lv_button_create(ui_popup20);
    lv_obj_set_width(ui_deletbtn2no, 60);
    lv_obj_set_height(ui_deletbtn2no, 38);
    lv_obj_set_x(ui_deletbtn2no, 60);
    lv_obj_set_y(ui_deletbtn2no, 41);
    lv_obj_set_align(ui_deletbtn2no, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletbtn2no, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_deletbtn2no, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_deletbtn2no, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deletbtn2no, lv_color_hex(0xEA2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deletbtn2no, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deletbtn2no, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deletbtn2no, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deletbtn2no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_deletbtn2no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_deletbtn2no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt10 = lv_label_create(ui_deletbtn2no);
    lv_obj_set_width(ui_plustxt10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt10, _("no"));
    lv_obj_set_style_text_color(ui_plustxt10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletbtn2ok = lv_button_create(ui_popup20);
    lv_obj_set_width(ui_deletbtn2ok, 60);
    lv_obj_set_height(ui_deletbtn2ok, 38);
    lv_obj_set_x(ui_deletbtn2ok, -59);
    lv_obj_set_y(ui_deletbtn2ok, 42);
    lv_obj_set_align(ui_deletbtn2ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletbtn2ok, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_deletbtn2ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_deletbtn2ok, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deletbtn2ok, lv_color_hex(0x27EA39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deletbtn2ok, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deletbtn2ok, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deletbtn2ok, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deletbtn2ok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_deletbtn2ok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_deletbtn2ok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt11 = lv_label_create(ui_deletbtn2ok);
    lv_obj_set_width(ui_plustxt11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt11, _("yes"));
    lv_obj_set_style_text_color(ui_plustxt11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_gotoadd, ui_event_gotoadd, LV_EVENT_ALL, NULL);
    uic_employee = ui_employee;
    uic_mainemployee = ui_mainemployee;
    uic_employeetemple = ui_employeetemple;
    uic_txtid = ui_txtid;
    uic_employeename = ui_employeename;
    uic_editbtn = ui_editbtn;
    uic_editimage = ui_editimage;
    uic_deletbtn = ui_deletbtn;
    uic_deletimage = ui_deletimage;
    uic_idtxt = ui_idtxt;
    uic_backtomenu = ui_backtomenu;
    uic_backimg = ui_backimg;
    uic_employeetxt = ui_employeetxt;
    uic_gotoadd = ui_gotoadd;
    uic_plustxt2 = ui_plustxt2;
    uic_popup20 = ui_popup20;
    uic_deletbtn2no = ui_deletbtn2no;
    uic_deletbtn2ok = ui_deletbtn2ok;

}

void ui_employee_screen_destroy(void)
{
    if(ui_employee) lv_obj_del(ui_employee);

    // NULL screen variables
    uic_employee = NULL;
    ui_employee = NULL;
    ui_mainpanel = NULL;
    uic_mainemployee = NULL;
    ui_mainemployee = NULL;
    uic_employeetemple = NULL;
    ui_employeetemple = NULL;
    uic_txtid = NULL;
    ui_txtid = NULL;
    uic_employeename = NULL;
    ui_employeename = NULL;
    uic_editbtn = NULL;
    ui_editbtn = NULL;
    uic_editimage = NULL;
    ui_editimage = NULL;
    uic_deletbtn = NULL;
    ui_deletbtn = NULL;
    uic_deletimage = NULL;
    ui_deletimage = NULL;
    uic_idtxt = NULL;
    ui_idtxt = NULL;
    uic_backtomenu = NULL;
    ui_backtomenu = NULL;
    uic_backimg = NULL;
    ui_backimg = NULL;
    uic_employeetxt = NULL;
    ui_employeetxt = NULL;
    uic_gotoadd = NULL;
    ui_gotoadd = NULL;
    uic_plustxt2 = NULL;
    ui_plustxt2 = NULL;
    uic_popup20 = NULL;
    ui_popup20 = NULL;
    ui_plustxt9 = NULL;
    uic_deletbtn2no = NULL;
    ui_deletbtn2no = NULL;
    ui_plustxt10 = NULL;
    uic_deletbtn2ok = NULL;
    ui_deletbtn2ok = NULL;
    ui_plustxt11 = NULL;

}

void ui_employee_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_mainemployee) && lv_obj_is_valid(ui_mainemployee)) lv_label_set_text(ui_mainemployee, _("employee name"));
    if((ui_idtxt) && lv_obj_is_valid(ui_idtxt)) lv_label_set_text(ui_idtxt, _("id"));
    if((ui_employeetxt) && lv_obj_is_valid(ui_employeetxt)) lv_label_set_text(ui_employeetxt, _("employee"));
    if((ui_plustxt9) && lv_obj_is_valid(ui_plustxt9)) lv_label_set_text(ui_plustxt9, _("are you sure?"));
    if((ui_plustxt10) && lv_obj_is_valid(ui_plustxt10)) lv_label_set_text(ui_plustxt10, _("no"));
    if((ui_plustxt11) && lv_obj_is_valid(ui_plustxt11)) lv_label_set_text(ui_plustxt11, _("yes"));

}
