// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Image2200;
lv_obj_t * uic_okpopup10;
lv_obj_t * uic_editemployeename;
lv_obj_t * uic_editemployeekey;
lv_obj_t * uic_okedit;
lv_obj_t * uic_okedit;
lv_obj_t * uic_editemployee;
lv_obj_t * ui_editemployee = NULL;
lv_obj_t * ui_backtomenu1 = NULL;
lv_obj_t * ui_backimg1 = NULL;
lv_obj_t * ui_okedit = NULL;
lv_obj_t * ui_okedit11 = NULL;
lv_obj_t * ui_popup1 = NULL;
lv_obj_t * ui_plustxt12 = NULL;
lv_obj_t * ui_deletbtn3 = NULL;
lv_obj_t * ui_plustxt13 = NULL;
lv_obj_t * ui_editbtn3 = NULL;
lv_obj_t * ui_plustxt14 = NULL;
lv_obj_t * ui_editemployeekey = NULL;
lv_obj_t * ui_editemployeename = NULL;
lv_obj_t * ui_okpopup10 = NULL;
lv_obj_t * ui_Image2200 = NULL;
lv_obj_t * ui_plustxt15 = NULL;
// event funtions
void ui_event_backtomenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_employee, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_employee_screen_init);
    }
}

void ui_event_okedit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addemployee, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_addemployee_screen_init);
    }
}

// build funtions

void ui_editemployee_screen_init(void)
{
    ui_editemployee = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_editemployee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_editemployee, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_editemployee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtomenu1 = lv_button_create(ui_editemployee);
    lv_obj_set_width(ui_backtomenu1, 50);
    lv_obj_set_height(ui_backtomenu1, 38);
    lv_obj_set_x(ui_backtomenu1, -202);
    lv_obj_set_y(ui_backtomenu1, -114);
    lv_obj_set_align(ui_backtomenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu1, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu1, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg1 = lv_image_create(ui_backtomenu1);
    lv_image_set_src(ui_backimg1, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okedit = lv_button_create(ui_editemployee);
    lv_obj_set_width(ui_okedit, 50);
    lv_obj_set_height(ui_okedit, 38);
    lv_obj_set_x(ui_okedit, 201);
    lv_obj_set_y(ui_okedit, -114);
    lv_obj_set_align(ui_okedit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okedit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_okedit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_okedit, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_okedit, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okedit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_okedit, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_okedit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_okedit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_okedit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_okedit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okedit11 = lv_image_create(ui_okedit);
    lv_image_set_src(ui_okedit11, &ui_img_1790866911);
    lv_obj_set_width(ui_okedit11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okedit11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okedit11, -1);
    lv_obj_set_y(ui_okedit11, -1);
    lv_obj_set_align(ui_okedit11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okedit11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_okedit11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup1 = lv_obj_create(ui_editemployee);
    lv_obj_set_width(ui_popup1, 251);
    lv_obj_set_height(ui_popup1, 149);
    lv_obj_set_x(ui_popup1, 0);
    lv_obj_set_y(ui_popup1, -14);
    lv_obj_set_align(ui_popup1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_popup1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_popup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_popup1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_popup1, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_popup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_popup1, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_popup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_popup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_popup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_popup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt12 = lv_label_create(ui_popup1);
    lv_obj_set_width(ui_plustxt12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt12, 0);
    lv_obj_set_y(ui_plustxt12, -21);
    lv_obj_set_align(ui_plustxt12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt12, _("are you sure?"));
    lv_obj_set_style_text_color(ui_plustxt12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletbtn3 = lv_button_create(ui_popup1);
    lv_obj_set_width(ui_deletbtn3, 60);
    lv_obj_set_height(ui_deletbtn3, 38);
    lv_obj_set_x(ui_deletbtn3, 60);
    lv_obj_set_y(ui_deletbtn3, 41);
    lv_obj_set_align(ui_deletbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_deletbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_deletbtn3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deletbtn3, lv_color_hex(0xEA2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deletbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deletbtn3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deletbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deletbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_deletbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_deletbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt13 = lv_label_create(ui_deletbtn3);
    lv_obj_set_width(ui_plustxt13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt13, _("no"));
    lv_obj_set_style_text_color(ui_plustxt13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editbtn3 = lv_button_create(ui_popup1);
    lv_obj_set_width(ui_editbtn3, 60);
    lv_obj_set_height(ui_editbtn3, 38);
    lv_obj_set_x(ui_editbtn3, -59);
    lv_obj_set_y(ui_editbtn3, 42);
    lv_obj_set_align(ui_editbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_editbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_editbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_editbtn3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_editbtn3, lv_color_hex(0x27EA39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_editbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_editbtn3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_editbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_editbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_editbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_editbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plustxt14 = lv_label_create(ui_editbtn3);
    lv_obj_set_width(ui_plustxt14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plustxt14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt14, _("yes"));
    lv_obj_set_style_text_color(ui_plustxt14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editemployeekey = lv_keyboard_create(ui_editemployee);
    lv_obj_set_height(ui_editemployeekey, 141);
    lv_obj_set_width(ui_editemployeekey, lv_pct(100));
    lv_obj_set_x(ui_editemployeekey, 0);
    lv_obj_set_y(ui_editemployeekey, 64);
    lv_obj_set_align(ui_editemployeekey, LV_ALIGN_CENTER);

    ui_editemployeename = lv_textarea_create(ui_editemployee);
    lv_obj_set_width(ui_editemployeename, 238);
    lv_obj_set_height(ui_editemployeename, 58);
    lv_obj_set_x(ui_editemployeename, 0);
    lv_obj_set_y(ui_editemployeename, -63);
    lv_obj_set_align(ui_editemployeename, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_editemployeename, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_editemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_editemployeename, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_editemployeename, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_editemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_editemployeename, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_editemployeename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okpopup10 = lv_obj_create(ui_editemployee);
    lv_obj_set_width(ui_okpopup10, 251);
    lv_obj_set_height(ui_okpopup10, 149);
    lv_obj_set_x(ui_okpopup10, 0);
    lv_obj_set_y(ui_okpopup10, -14);
    lv_obj_set_align(ui_okpopup10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okpopup10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_okpopup10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_okpopup10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_okpopup10, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okpopup10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_okpopup10, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_okpopup10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_okpopup10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_okpopup10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_okpopup10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2200 = lv_image_create(ui_okpopup10);
    lv_image_set_src(ui_Image2200, &ui_img_670821478);
    lv_obj_set_width(ui_Image2200, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2200, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2200, 0);
    lv_obj_set_y(ui_Image2200, -25);
    lv_obj_set_align(ui_Image2200, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2200, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2200, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plustxt15 = lv_label_create(ui_okpopup10);
    lv_obj_set_width(ui_plustxt15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plustxt15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plustxt15, 1);
    lv_obj_set_y(ui_plustxt15, 31);
    lv_obj_set_align(ui_plustxt15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plustxt15, _("Done successfully"));
    lv_obj_set_style_text_color(ui_plustxt15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plustxt15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plustxt15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backtomenu1, ui_event_backtomenu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_okedit, ui_event_okedit, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_editemployeekey, ui_editemployeename);
    uic_editemployee = ui_editemployee;
    uic_okedit = ui_okedit;
    uic_okedit = ui_okedit11;
    uic_editemployeekey = ui_editemployeekey;
    uic_editemployeename = ui_editemployeename;
    uic_okpopup10 = ui_okpopup10;
    uic_Image2200 = ui_Image2200;

}

void ui_editemployee_screen_destroy(void)
{
    if(ui_editemployee) lv_obj_del(ui_editemployee);

    // NULL screen variables
    uic_editemployee = NULL;
    ui_editemployee = NULL;
    ui_backtomenu1 = NULL;
    ui_backimg1 = NULL;
    uic_okedit = NULL;
    ui_okedit = NULL;
    uic_okedit = NULL;
    ui_okedit11 = NULL;
    ui_popup1 = NULL;
    ui_plustxt12 = NULL;
    ui_deletbtn3 = NULL;
    ui_plustxt13 = NULL;
    ui_editbtn3 = NULL;
    ui_plustxt14 = NULL;
    uic_editemployeekey = NULL;
    ui_editemployeekey = NULL;
    uic_editemployeename = NULL;
    ui_editemployeename = NULL;
    uic_okpopup10 = NULL;
    ui_okpopup10 = NULL;
    uic_Image2200 = NULL;
    ui_Image2200 = NULL;
    ui_plustxt15 = NULL;

}

void ui_editemployee_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_plustxt12) && lv_obj_is_valid(ui_plustxt12)) lv_label_set_text(ui_plustxt12, _("are you sure?"));
    if((ui_plustxt13) && lv_obj_is_valid(ui_plustxt13)) lv_label_set_text(ui_plustxt13, _("no"));
    if((ui_plustxt14) && lv_obj_is_valid(ui_plustxt14)) lv_label_set_text(ui_plustxt14, _("yes"));
    if((ui_plustxt15) && lv_obj_is_valid(ui_plustxt15)) lv_label_set_text(ui_plustxt15, _("Done successfully"));

}
