// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_EMPLOYEE_H
#define UI_EMPLOYEE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_employee
extern void ui_employee_screen_init(void);
extern void ui_employee_screen_destroy(void);
extern void ui_employee_screen_relocalize(void);
extern lv_obj_t * ui_employee;
extern lv_obj_t * ui_mainpanel;
extern lv_obj_t * ui_mainemployee;
extern lv_obj_t * ui_employeetemple;
extern lv_obj_t * ui_txtid;
extern lv_obj_t * ui_employeename;
extern lv_obj_t * ui_editbtn;
extern lv_obj_t * ui_editimage;
extern lv_obj_t * ui_deletbtn;
extern lv_obj_t * ui_deletimage;
extern lv_obj_t * ui_idtxt;
extern lv_obj_t * ui_backtomenu;
extern lv_obj_t * ui_backimg;
extern lv_obj_t * ui_employeetxt;
extern void ui_event_gotoadd(lv_event_t * e);
extern lv_obj_t * ui_gotoadd;
extern lv_obj_t * ui_plustxt2;
extern lv_obj_t * ui_popup20;
extern lv_obj_t * ui_plustxt9;
extern lv_obj_t * ui_deletbtn2no;
extern lv_obj_t * ui_plustxt10;
extern lv_obj_t * ui_deletbtn2ok;
extern lv_obj_t * ui_plustxt11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_employee;
extern lv_obj_t * uic_mainemployee;
extern lv_obj_t * uic_employeetemple;
extern lv_obj_t * uic_txtid;
extern lv_obj_t * uic_employeename;
extern lv_obj_t * uic_editbtn;
extern lv_obj_t * uic_editimage;
extern lv_obj_t * uic_deletbtn;
extern lv_obj_t * uic_deletimage;
extern lv_obj_t * uic_idtxt;
extern lv_obj_t * uic_backtomenu;
extern lv_obj_t * uic_backimg;
extern lv_obj_t * uic_employeetxt;
extern lv_obj_t * uic_gotoadd;
extern lv_obj_t * uic_plustxt2;
extern lv_obj_t * uic_popup20;
extern lv_obj_t * uic_deletbtn2no;
extern lv_obj_t * uic_deletbtn2ok;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

