// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_EDITEMPLOYEE_H
#define UI_EDITEMPLOYEE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_editemployee
extern void ui_editemployee_screen_init(void);
extern void ui_editemployee_screen_destroy(void);
extern void ui_editemployee_screen_relocalize(void);
extern lv_obj_t * ui_editemployee;
extern void ui_event_backtomenu1(lv_event_t * e);
extern lv_obj_t * ui_backtomenu1;
extern lv_obj_t * ui_backimg1;
extern void ui_event_okedit(lv_event_t * e);
extern lv_obj_t * ui_okedit;
extern lv_obj_t * ui_okedit11;
extern lv_obj_t * ui_popup1;
extern lv_obj_t * ui_plustxt12;
extern lv_obj_t * ui_deletbtn3;
extern lv_obj_t * ui_plustxt13;
extern lv_obj_t * ui_editbtn3;
extern lv_obj_t * ui_plustxt14;
extern lv_obj_t * ui_editemployeekey;
extern lv_obj_t * ui_editemployeename;
extern lv_obj_t * ui_okpopup10;
extern lv_obj_t * ui_Image2200;
extern lv_obj_t * ui_plustxt15;
// CUSTOM VARIABLES
extern lv_obj_t * uic_editemployee;
extern lv_obj_t * uic_okedit;
extern lv_obj_t * uic_okedit;
extern lv_obj_t * uic_editemployeekey;
extern lv_obj_t * uic_editemployeename;
extern lv_obj_t * uic_okpopup10;
extern lv_obj_t * uic_Image2200;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

