// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_chosse;
lv_obj_t * uic_savetxt;
lv_obj_t * uic_savelang;
lv_obj_t * uic_droplang;
lv_obj_t * uic_langtxt;
lv_obj_t * uic_langset;
lv_obj_t * ui_langset = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_langtxt = NULL;
lv_obj_t * ui_droplang = NULL;
lv_obj_t * ui_savelang = NULL;
lv_obj_t * ui_savetxt = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_chosse = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_langset_screen_init(void)
{
    ui_langset = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_langset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_langset, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_langset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_langset);
    lv_obj_set_width(ui_Button5, 50);
    lv_obj_set_height(ui_Button5, 38);
    lv_obj_set_x(ui_Button5, -203);
    lv_obj_set_y(ui_Button5, -113);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_image_create(ui_Button5);
    lv_image_set_src(ui_Image29, &ui_img_1385604958);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_langtxt = lv_label_create(ui_langset);
    lv_obj_set_width(ui_langtxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_langtxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_langtxt, 0);
    lv_obj_set_y(ui_langtxt, -116);
    lv_obj_set_align(ui_langtxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_langtxt, _("language"));
    lv_obj_set_style_text_color(ui_langtxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_langtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_langtxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_droplang = lv_dropdown_create(ui_langset);
    lv_dropdown_set_options(ui_droplang, "arabic\nenglish\nfrance");
    lv_obj_set_width(ui_droplang, 414);
    lv_obj_set_height(ui_droplang, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_droplang, 0);
    lv_obj_set_y(ui_droplang, -19);
    lv_obj_set_align(ui_droplang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droplang, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_droplang, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droplang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_droplang, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_droplang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_droplang, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_droplang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_droplang, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_droplang, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_droplang), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_droplang), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droplang), lv_color_hex(0x141922),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droplang), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_droplang), lv_color_hex(0x2A303B),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_droplang), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_droplang), lv_color_hex(0xFFFFFF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_droplang), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_droplang), lv_color_hex(0x2D3138),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_droplang), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_savelang = lv_button_create(ui_langset);
    lv_obj_set_width(ui_savelang, 220);
    lv_obj_set_height(ui_savelang, 53);
    lv_obj_set_x(ui_savelang, -7);
    lv_obj_set_y(ui_savelang, 38);
    lv_obj_set_align(ui_savelang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_savelang, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_savelang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_savelang, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_savelang, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_savelang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_savelang, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_savelang, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_savelang, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_savelang, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_savelang, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_savelang, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_savelang, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_savelang, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_savelang, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_savetxt = lv_label_create(ui_savelang);
    lv_obj_set_width(ui_savetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_savetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_savetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_savetxt, _("save"));
    lv_obj_set_style_text_color(ui_savetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_savetxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_savetxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image30 = lv_image_create(ui_langset);
    lv_image_set_src(ui_Image30, &ui_img_567465477);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image30, -189);
    lv_obj_set_y(ui_Image30, -62);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chosse = lv_label_create(ui_langset);
    lv_obj_set_width(ui_chosse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chosse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chosse, -94);
    lv_obj_set_y(ui_chosse, -62);
    lv_obj_set_align(ui_chosse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chosse, _("chosse language"));
    lv_obj_set_style_text_color(ui_chosse, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chosse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chosse, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    uic_langset = ui_langset;
    uic_langtxt = ui_langtxt;
    uic_droplang = ui_droplang;
    uic_savelang = ui_savelang;
    uic_savetxt = ui_savetxt;
    uic_chosse = ui_chosse;

}

void ui_langset_screen_destroy(void)
{
    if(ui_langset) lv_obj_del(ui_langset);

    // NULL screen variables
    uic_langset = NULL;
    ui_langset = NULL;
    ui_Button5 = NULL;
    ui_Image29 = NULL;
    uic_langtxt = NULL;
    ui_langtxt = NULL;
    uic_droplang = NULL;
    ui_droplang = NULL;
    uic_savelang = NULL;
    ui_savelang = NULL;
    uic_savetxt = NULL;
    ui_savetxt = NULL;
    ui_Image30 = NULL;
    uic_chosse = NULL;
    ui_chosse = NULL;

}

void ui_langset_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_langtxt) && lv_obj_is_valid(ui_langtxt)) lv_label_set_text(ui_langtxt, _("language"));
    if((ui_savetxt) && lv_obj_is_valid(ui_savetxt)) lv_label_set_text(ui_savetxt, _("save"));
    if((ui_chosse) && lv_obj_is_valid(ui_chosse)) lv_label_set_text(ui_chosse, _("chosse language"));

}
