// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LANGSET_H
#define UI_LANGSET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_langset
extern void ui_langset_screen_init(void);
extern void ui_langset_screen_destroy(void);
extern void ui_langset_screen_relocalize(void);
extern lv_obj_t * ui_langset;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_langtxt;
extern lv_obj_t * ui_droplang;
extern lv_obj_t * ui_savelang;
extern lv_obj_t * ui_savetxt;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_chosse;
// CUSTOM VARIABLES
extern lv_obj_t * uic_langset;
extern lv_obj_t * uic_langtxt;
extern lv_obj_t * uic_droplang;
extern lv_obj_t * uic_savelang;
extern lv_obj_t * uic_savetxt;
extern lv_obj_t * uic_chosse;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

