// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_main_screen_relocalize(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_wifistat;
extern void ui_event_btnmenu(lv_event_t * e);
extern lv_obj_t * ui_btnmenu;
extern void ui_event_settingsbtn(lv_event_t * e);
extern lv_obj_t * ui_settingsbtn;
extern lv_obj_t * ui_setbtn;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_menubtn;
extern lv_obj_t * ui_datetxt;
extern lv_obj_t * ui_dayname;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_ampmtxt;
extern lv_obj_t * ui_welcometxt;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_readytxt;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_hour2;
extern lv_obj_t * ui_passpanel;
extern lv_obj_t * ui_keypasstxt;
extern lv_obj_t * ui_keypass;
extern void ui_event_backmain(lv_event_t * e);
extern lv_obj_t * ui_backmain;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_name;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_inorout;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image40;
// CUSTOM VARIABLES
extern lv_obj_t * uic_main;
extern lv_obj_t * uic_wifi;
extern lv_obj_t * uic_wifistat;
extern lv_obj_t * uic_btnmenu;
extern lv_obj_t * uic_settingsbtn;
extern lv_obj_t * uic_setbtn;
extern lv_obj_t * uic_menubtn;
extern lv_obj_t * uic_datetxt;
extern lv_obj_t * uic_dayname;
extern lv_obj_t * uic_hour;
extern lv_obj_t * uic_ampmtxt;
extern lv_obj_t * uic_welcometxt;
extern lv_obj_t * uic_readytxt;
extern lv_obj_t * uic_min;
extern lv_obj_t * uic_passpanel;
extern lv_obj_t * uic_keypasstxt;
extern lv_obj_t * uic_keypass;
extern lv_obj_t * uic_backmain;
extern lv_obj_t * uic_Panel4;
extern lv_obj_t * uic_name;
extern lv_obj_t * uic_inorout;
extern lv_obj_t * uic_Panel7;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

