// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Panel7;
lv_obj_t * uic_inorout;
lv_obj_t * uic_name;
lv_obj_t * uic_Panel4;
lv_obj_t * uic_backmain;
lv_obj_t * uic_keypass;
lv_obj_t * uic_keypasstxt;
lv_obj_t * uic_passpanel;
lv_obj_t * uic_min;
lv_obj_t * uic_readytxt;
lv_obj_t * uic_welcometxt;
lv_obj_t * uic_ampmtxt;
lv_obj_t * uic_hour;
lv_obj_t * uic_dayname;
lv_obj_t * uic_datetxt;
lv_obj_t * uic_menubtn;
lv_obj_t * uic_setbtn;
lv_obj_t * uic_settingsbtn;
lv_obj_t * uic_btnmenu;
lv_obj_t * uic_wifistat;
lv_obj_t * uic_wifi;
lv_obj_t * uic_main;
lv_obj_t * ui_main = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_wifistat = NULL;
lv_obj_t * ui_btnmenu = NULL;
lv_obj_t * ui_settingsbtn = NULL;
lv_obj_t * ui_setbtn = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_menubtn = NULL;
lv_obj_t * ui_datetxt = NULL;
lv_obj_t * ui_dayname = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_ampmtxt = NULL;
lv_obj_t * ui_welcometxt = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_readytxt = NULL;
lv_obj_t * ui_min = NULL;
lv_obj_t * ui_hour2 = NULL;
lv_obj_t * ui_passpanel = NULL;
lv_obj_t * ui_keypasstxt = NULL;
lv_obj_t * ui_keypass = NULL;
lv_obj_t * ui_backmain = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Image39 = NULL;
lv_obj_t * ui_name = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_inorout = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Image40 = NULL;
// event funtions
void ui_event_btnmenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

void ui_event_settingsbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settings_screen_init);
    }
}

void ui_event_backmain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_main_screen_init);
    }
}

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_main, &ui_img_background_480x272_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_label_create(ui_main);
    lv_obj_set_width(ui_wifi, 19);
    lv_obj_set_height(ui_wifi, 21);
    lv_obj_set_x(ui_wifi, 198);
    lv_obj_set_y(ui_wifi, -122);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifi, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_wifi, "");
    lv_obj_set_style_text_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistat = lv_label_create(ui_main);
    lv_obj_set_width(ui_wifistat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifistat, 205);
    lv_obj_set_y(ui_wifistat, -122);
    lv_obj_set_align(ui_wifistat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifistat, "s");
    lv_obj_set_style_text_color(ui_wifistat, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifistat, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnmenu = lv_button_create(ui_main);
    lv_obj_set_width(ui_btnmenu, 145);
    lv_obj_set_height(ui_btnmenu, 47);
    lv_obj_set_x(ui_btnmenu, 148);
    lv_obj_set_y(ui_btnmenu, -44);
    lv_obj_set_align(ui_btnmenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnmenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnmenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnmenu, lv_color_hex(0x007CE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnmenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnmenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsbtn = lv_button_create(ui_main);
    lv_obj_set_width(ui_settingsbtn, 145);
    lv_obj_set_height(ui_settingsbtn, 47);
    lv_obj_set_x(ui_settingsbtn, 148);
    lv_obj_set_y(ui_settingsbtn, 27);
    lv_obj_set_align(ui_settingsbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsbtn, lv_color_hex(0x19293F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsbtn, 254, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_settingsbtn, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_settingsbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setbtn = lv_label_create(ui_main);
    lv_obj_set_width(ui_setbtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setbtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setbtn, 131);
    lv_obj_set_y(ui_setbtn, 28);
    lv_obj_set_align(ui_setbtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setbtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setbtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_setbtn, _("settings"));
    lv_obj_set_style_text_color(ui_setbtn, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setbtn, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_main);
    lv_image_set_src(ui_Image5, &ui_img_724231620);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 195);
    lv_obj_set_y(ui_Image5, 28);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_main);
    lv_image_set_src(ui_Image6, &ui_img_706591335);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 197);
    lv_obj_set_y(ui_Image6, -44);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menubtn = lv_label_create(ui_main);
    lv_obj_set_width(ui_menubtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menubtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menubtn, 121);
    lv_obj_set_y(ui_menubtn, -44);
    lv_obj_set_align(ui_menubtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menubtn, _("menu"));
    lv_obj_set_style_text_color(ui_menubtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menubtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menubtn, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetxt = lv_label_create(ui_main);
    lv_obj_set_width(ui_datetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetxt, -178);
    lv_obj_set_y(ui_datetxt, -117);
    lv_obj_set_align(ui_datetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetxt, "2025/02/10");
    lv_obj_set_style_text_color(ui_datetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetxt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayname = lv_label_create(ui_main);
    lv_obj_set_width(ui_dayname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayname, -195);
    lv_obj_set_y(ui_dayname, -99);
    lv_obj_set_align(ui_dayname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dayname, "monday");
    lv_obj_set_style_text_color(ui_dayname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayname, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_main);
    lv_obj_set_width(ui_hour, 64);
    lv_obj_set_height(ui_hour, 47);
    lv_obj_set_x(ui_hour, -166);
    lv_obj_set_y(ui_hour, -44);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "02");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ampmtxt = lv_label_create(ui_main);
    lv_obj_set_width(ui_ampmtxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ampmtxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ampmtxt, -37);
    lv_obj_set_y(ui_ampmtxt, -32);
    lv_obj_set_align(ui_ampmtxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ampmtxt, "AM");
    lv_obj_set_style_text_color(ui_ampmtxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampmtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_welcometxt = lv_label_create(ui_main);
    lv_obj_set_width(ui_welcometxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_welcometxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_welcometxt, -72);
    lv_obj_set_y(ui_welcometxt, -9);
    lv_obj_set_align(ui_welcometxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_welcometxt, _("welcome"));
    lv_obj_set_style_text_color(ui_welcometxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_welcometxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcometxt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_main);
    lv_obj_set_width(ui_Panel2, 101);
    lv_obj_set_height(ui_Panel2, 23);
    lv_obj_set_x(ui_Panel2, -87);
    lv_obj_set_y(ui_Panel2, 22);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x19293F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x19293F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_main);
    lv_obj_set_width(ui_Panel3, 10);
    lv_obj_set_height(ui_Panel3, 11);
    lv_obj_set_x(ui_Panel3, -57);
    lv_obj_set_y(ui_Panel3, 22);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x7FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x7FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_readytxt = lv_label_create(ui_main);
    lv_obj_set_width(ui_readytxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_readytxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_readytxt, -95);
    lv_obj_set_y(ui_readytxt, 22);
    lv_obj_set_align(ui_readytxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_readytxt, _("Ready"));
    lv_obj_set_style_text_color(ui_readytxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_readytxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_readytxt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_main);
    lv_obj_set_width(ui_min, 65);
    lv_obj_set_height(ui_min, 47);
    lv_obj_set_x(ui_min, -84);
    lv_obj_set_y(ui_min, -44);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min, "02");
    lv_obj_set_style_text_color(ui_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_min, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour2 = lv_label_create(ui_main);
    lv_obj_set_width(ui_hour2, 10);
    lv_obj_set_height(ui_hour2, 47);
    lv_obj_set_x(ui_hour2, -126);
    lv_obj_set_y(ui_hour2, -44);
    lv_obj_set_align(ui_hour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour2, ":");
    lv_obj_set_style_text_color(ui_hour2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passpanel = lv_obj_create(ui_main);
    lv_obj_set_width(ui_passpanel, lv_pct(100));
    lv_obj_set_height(ui_passpanel, lv_pct(100));
    lv_obj_set_align(ui_passpanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_passpanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_passpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_passpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passpanel, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_passpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_passpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keypasstxt = lv_textarea_create(ui_passpanel);
    lv_obj_set_width(ui_keypasstxt, 150);
    lv_obj_set_height(ui_keypasstxt, 38);
    lv_obj_set_x(ui_keypasstxt, 0);
    lv_obj_set_y(ui_keypasstxt, -67);
    lv_obj_set_align(ui_keypasstxt, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_keypasstxt, 4);
    lv_textarea_set_password_mode(ui_keypasstxt, true);
    lv_obj_remove_flag(ui_keypasstxt, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_keypasstxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_keypasstxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_keypasstxt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_keypasstxt, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keypasstxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_keypasstxt, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_keypasstxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keypass = lv_keyboard_create(ui_passpanel);
    lv_keyboard_set_mode(ui_keypass, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_keypass, 251);
    lv_obj_set_height(ui_keypass, 120);
    lv_obj_set_x(ui_keypass, 0);
    lv_obj_set_y(ui_keypass, 23);
    lv_obj_set_align(ui_keypass, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_keypass, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_keypass, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keypass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_keypass, lv_color_hex(0x141922), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keypass, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_keypass, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_keypass, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_backmain = lv_button_create(ui_passpanel);
    lv_obj_set_width(ui_backmain, 50);
    lv_obj_set_height(ui_backmain, 38);
    lv_obj_set_x(ui_backmain, -202);
    lv_obj_set_y(ui_backmain, -114);
    lv_obj_set_align(ui_backmain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backmain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backmain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backmain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backmain, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backmain, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backmain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backmain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backmain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image32 = lv_image_create(ui_backmain);
    lv_image_set_src(ui_Image32, &ui_img_1385604958);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_main);
    lv_obj_set_width(ui_Panel4, 270);
    lv_obj_set_height(ui_Panel4, 165);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image39 = lv_image_create(ui_Panel4);
    lv_image_set_src(ui_Image39, &ui_img_565519698);
    lv_obj_set_width(ui_Image39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image39, -4);
    lv_obj_set_y(ui_Image39, -37);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_name = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_name, 118);
    lv_obj_set_y(ui_name, -48);
    lv_obj_set_align(ui_name, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_name, "name");
    lv_obj_set_style_text_color(ui_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_name, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 37);
    lv_obj_set_y(ui_Label5, -48);
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5, _("welcome"));
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inorout = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_inorout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inorout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inorout, 0);
    lv_obj_set_y(ui_inorout, 48);
    lv_obj_set_align(ui_inorout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_inorout, _("text"));
    lv_obj_set_style_text_color(ui_inorout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inorout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inorout, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_main);
    lv_obj_set_width(ui_Panel7, 270);
    lv_obj_set_height(ui_Panel7, 165);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image40 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image40, &ui_img_881979347);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnmenu, ui_event_btnmenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsbtn, ui_event_settingsbtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_keypass, ui_keypasstxt);
    lv_obj_add_event_cb(ui_backmain, ui_event_backmain, LV_EVENT_ALL, NULL);
    uic_main = ui_main;
    uic_wifi = ui_wifi;
    uic_wifistat = ui_wifistat;
    uic_btnmenu = ui_btnmenu;
    uic_settingsbtn = ui_settingsbtn;
    uic_setbtn = ui_setbtn;
    uic_menubtn = ui_menubtn;
    uic_datetxt = ui_datetxt;
    uic_dayname = ui_dayname;
    uic_hour = ui_hour;
    uic_ampmtxt = ui_ampmtxt;
    uic_welcometxt = ui_welcometxt;
    uic_readytxt = ui_readytxt;
    uic_min = ui_min;
    uic_passpanel = ui_passpanel;
    uic_keypasstxt = ui_keypasstxt;
    uic_keypass = ui_keypass;
    uic_backmain = ui_backmain;
    uic_Panel4 = ui_Panel4;
    uic_name = ui_name;
    uic_inorout = ui_inorout;
    uic_Panel7 = ui_Panel7;

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    uic_main = NULL;
    ui_main = NULL;
    uic_wifi = NULL;
    ui_wifi = NULL;
    uic_wifistat = NULL;
    ui_wifistat = NULL;
    uic_btnmenu = NULL;
    ui_btnmenu = NULL;
    uic_settingsbtn = NULL;
    ui_settingsbtn = NULL;
    uic_setbtn = NULL;
    ui_setbtn = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    uic_menubtn = NULL;
    ui_menubtn = NULL;
    uic_datetxt = NULL;
    ui_datetxt = NULL;
    uic_dayname = NULL;
    ui_dayname = NULL;
    uic_hour = NULL;
    ui_hour = NULL;
    uic_ampmtxt = NULL;
    ui_ampmtxt = NULL;
    uic_welcometxt = NULL;
    ui_welcometxt = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    uic_readytxt = NULL;
    ui_readytxt = NULL;
    uic_min = NULL;
    ui_min = NULL;
    ui_hour2 = NULL;
    uic_passpanel = NULL;
    ui_passpanel = NULL;
    uic_keypasstxt = NULL;
    ui_keypasstxt = NULL;
    uic_keypass = NULL;
    ui_keypass = NULL;
    uic_backmain = NULL;
    ui_backmain = NULL;
    ui_Image32 = NULL;
    uic_Panel4 = NULL;
    ui_Panel4 = NULL;
    ui_Image39 = NULL;
    uic_name = NULL;
    ui_name = NULL;
    ui_Label5 = NULL;
    uic_inorout = NULL;
    ui_inorout = NULL;
    uic_Panel7 = NULL;
    ui_Panel7 = NULL;
    ui_Image40 = NULL;

}

void ui_main_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_setbtn) && lv_obj_is_valid(ui_setbtn)) lv_label_set_text(ui_setbtn, _("settings"));
    if((ui_menubtn) && lv_obj_is_valid(ui_menubtn)) lv_label_set_text(ui_menubtn, _("menu"));
    if((ui_welcometxt) && lv_obj_is_valid(ui_welcometxt)) lv_label_set_text(ui_welcometxt, _("welcome"));
    if((ui_readytxt) && lv_obj_is_valid(ui_readytxt)) lv_label_set_text(ui_readytxt, _("Ready"));
    if((ui_Label5) && lv_obj_is_valid(ui_Label5)) lv_label_set_text(ui_Label5, _("welcome"));
    if((ui_inorout) && lv_obj_is_valid(ui_inorout)) lv_label_set_text(ui_inorout, _("text"));

}
