// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_changetorecord;
lv_obj_t * uic_changetopassword;
lv_obj_t * uic_txtbtn3;
lv_obj_t * uic_changetoempo;
lv_obj_t * uic_menutxt;
lv_obj_t * uic_menu;
lv_obj_t * ui_menu = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Image33 = NULL;
lv_obj_t * ui_menutxt = NULL;
lv_obj_t * ui_changetoempo = NULL;
lv_obj_t * ui_txtbtn3 = NULL;
lv_obj_t * ui_Image34 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_changetopassword = NULL;
lv_obj_t * ui_Image36 = NULL;
lv_obj_t * ui_txtbtn9 = NULL;
lv_obj_t * ui_Image35 = NULL;
lv_obj_t * ui_changetorecord = NULL;
lv_obj_t * ui_Image38 = NULL;
lv_obj_t * ui_txtbtn10 = NULL;
lv_obj_t * ui_Image37 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_main_screen_init);
    }
}

void ui_event_changetopassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_changepassscreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiset_screen_init);
    }
}

// build funtions

void ui_menu_screen_init(void)
{
    ui_menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menu, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_menu);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 38);
    lv_obj_set_x(ui_Button2, -202);
    lv_obj_set_y(ui_Button2, -114);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image33 = lv_image_create(ui_Button2);
    lv_image_set_src(ui_Image33, &ui_img_1385604958);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menutxt = lv_label_create(ui_menu);
    lv_obj_set_width(ui_menutxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menutxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menutxt, 0);
    lv_obj_set_y(ui_menutxt, -120);
    lv_obj_set_align(ui_menutxt, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menutxt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menutxt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_menutxt, _("menu"));
    lv_obj_set_style_text_color(ui_menutxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menutxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menutxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetoempo = lv_button_create(ui_menu);
    lv_obj_set_width(ui_changetoempo, 220);
    lv_obj_set_height(ui_changetoempo, 58);
    lv_obj_set_x(ui_changetoempo, -121);
    lv_obj_set_y(ui_changetoempo, -52);
    lv_obj_set_align(ui_changetoempo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetoempo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetoempo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetoempo, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetoempo, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetoempo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetoempo, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetoempo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetoempo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetoempo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetoempo, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetoempo, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetoempo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetoempo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetoempo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn3 = lv_label_create(ui_menu);
    lv_obj_set_width(ui_txtbtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn3, -137);
    lv_obj_set_y(ui_txtbtn3, -52);
    lv_obj_set_align(ui_txtbtn3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn3, _("employee"));
    lv_obj_set_style_text_color(ui_txtbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image34 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image34, &ui_img_1832640421);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image34, -34);
    lv_obj_set_y(ui_Image34, -51);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image28, &ui_img_350414076);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image28, -205);
    lv_obj_set_y(ui_Image28, -51);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changetopassword = lv_button_create(ui_menu);
    lv_obj_set_width(ui_changetopassword, 220);
    lv_obj_set_height(ui_changetopassword, 58);
    lv_obj_set_x(ui_changetopassword, -121);
    lv_obj_set_y(ui_changetopassword, 39);
    lv_obj_set_align(ui_changetopassword, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetopassword, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetopassword, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetopassword, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetopassword, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetopassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetopassword, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetopassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetopassword, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetopassword, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetopassword, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetopassword, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetopassword, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetopassword, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetopassword, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image36 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image36, &ui_img_1832640421);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image36, -33);
    lv_obj_set_y(ui_Image36, 39);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtbtn9 = lv_label_create(ui_menu);
    lv_obj_set_width(ui_txtbtn9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn9, -134);
    lv_obj_set_y(ui_txtbtn9, 37);
    lv_obj_set_align(ui_txtbtn9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn9, _("password"));
    lv_obj_set_style_text_color(ui_txtbtn9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image35 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image35, &ui_img_140600673);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image35, -205);
    lv_obj_set_y(ui_Image35, 39);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changetorecord = lv_button_create(ui_menu);
    lv_obj_set_width(ui_changetorecord, 216);
    lv_obj_set_height(ui_changetorecord, 58);
    lv_obj_set_x(ui_changetorecord, 120);
    lv_obj_set_y(ui_changetorecord, -52);
    lv_obj_set_align(ui_changetorecord, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetorecord, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetorecord, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetorecord, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetorecord, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetorecord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetorecord, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetorecord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetorecord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetorecord, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetorecord, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetorecord, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetorecord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetorecord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetorecord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image38 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image38, &ui_img_1832640421);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image38, 206);
    lv_obj_set_y(ui_Image38, -52);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtbtn10 = lv_label_create(ui_menu);
    lv_obj_set_width(ui_txtbtn10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn10, 99);
    lv_obj_set_y(ui_txtbtn10, -52);
    lv_obj_set_align(ui_txtbtn10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn10, _("Record"));
    lv_obj_set_style_text_color(ui_txtbtn10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image37 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image37, &ui_img_1813113080);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image37, 38);
    lv_obj_set_y(ui_Image37, -51);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetopassword, ui_event_changetopassword, LV_EVENT_ALL, NULL);
    uic_menu = ui_menu;
    uic_menutxt = ui_menutxt;
    uic_changetoempo = ui_changetoempo;
    uic_txtbtn3 = ui_txtbtn3;
    uic_changetopassword = ui_changetopassword;
    uic_changetorecord = ui_changetorecord;

}

void ui_menu_screen_destroy(void)
{
    if(ui_menu) lv_obj_del(ui_menu);

    // NULL screen variables
    uic_menu = NULL;
    ui_menu = NULL;
    ui_Button2 = NULL;
    ui_Image33 = NULL;
    uic_menutxt = NULL;
    ui_menutxt = NULL;
    uic_changetoempo = NULL;
    ui_changetoempo = NULL;
    uic_txtbtn3 = NULL;
    ui_txtbtn3 = NULL;
    ui_Image34 = NULL;
    ui_Image28 = NULL;
    uic_changetopassword = NULL;
    ui_changetopassword = NULL;
    ui_Image36 = NULL;
    ui_txtbtn9 = NULL;
    ui_Image35 = NULL;
    uic_changetorecord = NULL;
    ui_changetorecord = NULL;
    ui_Image38 = NULL;
    ui_txtbtn10 = NULL;
    ui_Image37 = NULL;

}

void ui_menu_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_menutxt) && lv_obj_is_valid(ui_menutxt)) lv_label_set_text(ui_menutxt, _("menu"));
    if((ui_txtbtn3) && lv_obj_is_valid(ui_txtbtn3)) lv_label_set_text(ui_txtbtn3, _("employee"));
    if((ui_txtbtn9) && lv_obj_is_valid(ui_txtbtn9)) lv_label_set_text(ui_txtbtn9, _("password"));
    if((ui_txtbtn10) && lv_obj_is_valid(ui_txtbtn10)) lv_label_set_text(ui_txtbtn10, _("Record"));

}
