// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_menu
extern void ui_menu_screen_init(void);
extern void ui_menu_screen_destroy(void);
extern void ui_menu_screen_relocalize(void);
extern lv_obj_t * ui_menu;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_menutxt;
extern lv_obj_t * ui_changetoempo;
extern lv_obj_t * ui_txtbtn3;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image28;
extern void ui_event_changetopassword(lv_event_t * e);
extern lv_obj_t * ui_changetopassword;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_txtbtn9;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_changetorecord;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_txtbtn10;
extern lv_obj_t * ui_Image37;
// CUSTOM VARIABLES
extern lv_obj_t * uic_menu;
extern lv_obj_t * uic_menutxt;
extern lv_obj_t * uic_changetoempo;
extern lv_obj_t * uic_txtbtn3;
extern lv_obj_t * uic_changetopassword;
extern lv_obj_t * uic_changetorecord;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

