// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_RECORDSCREEN_H
#define UI_RECORDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_recordscreen
extern void ui_recordscreen_screen_init(void);
extern void ui_recordscreen_screen_destroy(void);
extern void ui_recordscreen_screen_relocalize(void);
extern lv_obj_t * ui_recordscreen;
extern void ui_event_backtomenu2(lv_event_t * e);
extern lv_obj_t * ui_backtomenu2;
extern lv_obj_t * ui_backimg2;
extern lv_obj_t * ui_namedropdown;
extern lv_obj_t * ui_employeetxt2;
extern lv_obj_t * ui_datedropdown;
extern lv_obj_t * ui_mainpanel3;
extern lv_obj_t * ui_employeetemple2;
extern lv_obj_t * ui_employeetxt3;
extern lv_obj_t * ui_employeetxtin;
extern lv_obj_t * ui_employeetxtoff;
extern lv_obj_t * ui_employeetxtout;
extern lv_obj_t * ui_currentdate;
// CUSTOM VARIABLES
extern lv_obj_t * uic_recordscreen;
extern lv_obj_t * uic_namedropdown;
extern lv_obj_t * uic_datedropdown;
extern lv_obj_t * uic_mainpanel3;
extern lv_obj_t * uic_employeetemple2;
extern lv_obj_t * uic_employeetxt3;
extern lv_obj_t * uic_employeetxtin;
extern lv_obj_t * uic_employeetxtoff;
extern lv_obj_t * uic_employeetxtout;
extern lv_obj_t * uic_currentdate;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

