// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_currentdate;
lv_obj_t * uic_employeetxtout;
lv_obj_t * uic_employeetxtoff;
lv_obj_t * uic_employeetxtin;
lv_obj_t * uic_employeetxt3;
lv_obj_t * uic_employeetemple2;
lv_obj_t * uic_mainpanel3;
lv_obj_t * uic_datedropdown;
lv_obj_t * uic_namedropdown;
lv_obj_t * uic_recordscreen;
lv_obj_t * ui_recordscreen = NULL;
lv_obj_t * ui_backtomenu2 = NULL;
lv_obj_t * ui_backimg2 = NULL;
lv_obj_t * ui_namedropdown = NULL;
lv_obj_t * ui_employeetxt2 = NULL;
lv_obj_t * ui_datedropdown = NULL;
lv_obj_t * ui_mainpanel3 = NULL;
lv_obj_t * ui_employeetemple2 = NULL;
lv_obj_t * ui_employeetxt3 = NULL;
lv_obj_t * ui_employeetxtin = NULL;
lv_obj_t * ui_employeetxtoff = NULL;
lv_obj_t * ui_employeetxtout = NULL;
lv_obj_t * ui_currentdate = NULL;
// event funtions
void ui_event_backtomenu2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_employee_screen_init);
    }
}

// build funtions

void ui_recordscreen_screen_init(void)
{
    ui_recordscreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_recordscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_recordscreen, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_recordscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_recordscreen, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_recordscreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_backtomenu2 = lv_button_create(ui_recordscreen);
    lv_obj_set_width(ui_backtomenu2, 50);
    lv_obj_set_height(ui_backtomenu2, 38);
    lv_obj_set_x(ui_backtomenu2, -202);
    lv_obj_set_y(ui_backtomenu2, -114);
    lv_obj_set_align(ui_backtomenu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomenu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtomenu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtomenu2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtomenu2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtomenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtomenu2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtomenu2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtomenu2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backtomenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backtomenu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backimg2 = lv_image_create(ui_backtomenu2);
    lv_image_set_src(ui_backimg2, &ui_img_1385604958);
    lv_obj_set_width(ui_backimg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backimg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backimg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backimg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backimg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_namedropdown = lv_dropdown_create(ui_recordscreen);
    lv_dropdown_set_options(ui_namedropdown, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_namedropdown, 150);
    lv_obj_set_height(ui_namedropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_namedropdown, 139);
    lv_obj_set_y(ui_namedropdown, -70);
    lv_obj_set_align(ui_namedropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_namedropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_namedropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_namedropdown, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_namedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_namedropdown, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_namedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_namedropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_namedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_namedropdown), lv_color_hex(0x141922),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_namedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_namedropdown), lv_color_hex(0x2A303B),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_namedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_namedropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_namedropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_employeetxt2 = lv_label_create(ui_recordscreen);
    lv_obj_set_width(ui_employeetxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxt2, 0);
    lv_obj_set_y(ui_employeetxt2, -119);
    lv_obj_set_align(ui_employeetxt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_employeetxt2, _("record"));
    lv_obj_set_style_text_color(ui_employeetxt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxt2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datedropdown = lv_dropdown_create(ui_recordscreen);
    lv_dropdown_set_options(ui_datedropdown, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_datedropdown, 150);
    lv_obj_set_height(ui_datedropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datedropdown, -40);
    lv_obj_set_y(ui_datedropdown, -68);
    lv_obj_set_align(ui_datedropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_datedropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_datedropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_datedropdown, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_datedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_datedropdown, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_datedropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_datedropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_datedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_datedropdown), lv_color_hex(0x141922),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_datedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_datedropdown), lv_color_hex(0x2A303B),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_datedropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_datedropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_datedropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_mainpanel3 = lv_obj_create(ui_recordscreen);
    lv_obj_set_height(ui_mainpanel3, 180);
    lv_obj_set_width(ui_mainpanel3, lv_pct(100));
    lv_obj_set_x(ui_mainpanel3, 0);
    lv_obj_set_y(ui_mainpanel3, 91);
    lv_obj_remove_flag(ui_mainpanel3, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_mainpanel3, LV_DIR_VER);
    lv_obj_set_style_radius(ui_mainpanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainpanel3, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainpanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetemple2 = lv_obj_create(ui_mainpanel3);
    lv_obj_set_width(ui_employeetemple2, 464);
    lv_obj_set_height(ui_employeetemple2, 58);
    lv_obj_set_x(ui_employeetemple2, -1);
    lv_obj_set_y(ui_employeetemple2, -12);
    lv_obj_set_align(ui_employeetemple2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_employeetemple2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_employeetemple2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_employeetemple2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_employeetemple2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_employeetemple2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_employeetemple2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_employeetemple2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_employeetemple2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_employeetemple2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetxt3 = lv_label_create(ui_employeetemple2);
    lv_obj_set_width(ui_employeetxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxt3, 13);
    lv_obj_set_y(ui_employeetxt3, 1);
    lv_label_set_text(ui_employeetxt3, _("name"));
    lv_obj_set_style_text_color(ui_employeetxt3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxt3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxt3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetxtin = lv_label_create(ui_employeetemple2);
    lv_obj_set_width(ui_employeetxtin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxtin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxtin, 145);
    lv_obj_set_y(ui_employeetxtin, 3);
    lv_label_set_text(ui_employeetxtin, _("in"));
    lv_obj_set_style_text_color(ui_employeetxtin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxtin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxtin, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetxtoff = lv_label_create(ui_employeetemple2);
    lv_obj_set_width(ui_employeetxtoff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxtoff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxtoff, 370);
    lv_obj_set_y(ui_employeetxtoff, 4);
    lv_label_set_text(ui_employeetxtoff, _("name"));
    lv_obj_set_style_text_color(ui_employeetxtoff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxtoff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxtoff, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_employeetxtout = lv_label_create(ui_employeetemple2);
    lv_obj_set_width(ui_employeetxtout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_employeetxtout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_employeetxtout, 256);
    lv_obj_set_y(ui_employeetxtout, 4);
    lv_label_set_text(ui_employeetxtout, _("out"));
    lv_obj_set_style_text_color(ui_employeetxtout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_employeetxtout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_employeetxtout, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentdate = lv_label_create(ui_mainpanel3);
    lv_obj_set_width(ui_currentdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentdate, 335);
    lv_obj_set_y(ui_currentdate, 3);
    lv_label_set_text(ui_currentdate, _("0000/00/00"));
    lv_obj_set_style_text_color(ui_currentdate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentdate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backtomenu2, ui_event_backtomenu2, LV_EVENT_ALL, NULL);
    uic_recordscreen = ui_recordscreen;
    uic_namedropdown = ui_namedropdown;
    uic_datedropdown = ui_datedropdown;
    uic_mainpanel3 = ui_mainpanel3;
    uic_employeetemple2 = ui_employeetemple2;
    uic_employeetxt3 = ui_employeetxt3;
    uic_employeetxtin = ui_employeetxtin;
    uic_employeetxtoff = ui_employeetxtoff;
    uic_employeetxtout = ui_employeetxtout;
    uic_currentdate = ui_currentdate;

}

void ui_recordscreen_screen_destroy(void)
{
    if(ui_recordscreen) lv_obj_del(ui_recordscreen);

    // NULL screen variables
    uic_recordscreen = NULL;
    ui_recordscreen = NULL;
    ui_backtomenu2 = NULL;
    ui_backimg2 = NULL;
    uic_namedropdown = NULL;
    ui_namedropdown = NULL;
    ui_employeetxt2 = NULL;
    uic_datedropdown = NULL;
    ui_datedropdown = NULL;
    uic_mainpanel3 = NULL;
    ui_mainpanel3 = NULL;
    uic_employeetemple2 = NULL;
    ui_employeetemple2 = NULL;
    uic_employeetxt3 = NULL;
    ui_employeetxt3 = NULL;
    uic_employeetxtin = NULL;
    ui_employeetxtin = NULL;
    uic_employeetxtoff = NULL;
    ui_employeetxtoff = NULL;
    uic_employeetxtout = NULL;
    ui_employeetxtout = NULL;
    uic_currentdate = NULL;
    ui_currentdate = NULL;

}

void ui_recordscreen_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_employeetxt2) && lv_obj_is_valid(ui_employeetxt2)) lv_label_set_text(ui_employeetxt2, _("record"));
    if((ui_employeetxt3) && lv_obj_is_valid(ui_employeetxt3)) lv_label_set_text(ui_employeetxt3, _("name"));
    if((ui_employeetxtin) && lv_obj_is_valid(ui_employeetxtin)) lv_label_set_text(ui_employeetxtin, _("in"));
    if((ui_employeetxtoff) && lv_obj_is_valid(ui_employeetxtoff)) lv_label_set_text(ui_employeetxtoff, _("name"));
    if((ui_employeetxtout) && lv_obj_is_valid(ui_employeetxtout)) lv_label_set_text(ui_employeetxtout, _("out"));
    if((ui_currentdate) && lv_obj_is_valid(ui_currentdate)) lv_label_set_text(ui_currentdate, _("0000/00/00"));

}
