// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern void ui_settings_screen_relocalize(void);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_wifi2;
extern lv_obj_t * ui_settext;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image1;
extern void ui_event_changetowifiset(lv_event_t * e);
extern lv_obj_t * ui_changetowifiset;
extern void ui_event_changetolangset(lv_event_t * e);
extern lv_obj_t * ui_changetolangset;
extern void ui_event_changetosoundset(lv_event_t * e);
extern lv_obj_t * ui_changetosoundset;
extern void ui_event_changetotimeset(lv_event_t * e);
extern lv_obj_t * ui_changetotimeset;
extern lv_obj_t * ui_changetoappset;
extern lv_obj_t * ui_changetoinfoset;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_txtbtn1;
extern lv_obj_t * ui_txtbtn4;
extern lv_obj_t * ui_txtbtn5;
extern lv_obj_t * ui_txtbtn6;
extern lv_obj_t * ui_txtbtn7;
extern lv_obj_t * ui_txtbtn8;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settings;
extern lv_obj_t * uic_settext;
extern lv_obj_t * uic_changetowifiset;
extern lv_obj_t * uic_changetolangset;
extern lv_obj_t * uic_changetosoundset;
extern lv_obj_t * uic_changetotimeset;
extern lv_obj_t * uic_changetoappset;
extern lv_obj_t * uic_changetoinfoset;
extern lv_obj_t * uic_txtbtn1;
extern lv_obj_t * uic_txtbtn4;
extern lv_obj_t * uic_txtbtn5;
extern lv_obj_t * uic_txtbtn6;
extern lv_obj_t * uic_txtbtn7;
extern lv_obj_t * uic_txtbtn8;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

