// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_mutetouch;
lv_obj_t * uic_soundtxt3;
lv_obj_t * uic_mutetxt;
lv_obj_t * uic_mute;
lv_obj_t * uic_soundval;
lv_obj_t * uic_soundtxt2;
lv_obj_t * uic_soundslider;
lv_obj_t * uic_soundtxt;
lv_obj_t * uic_soundset;
lv_obj_t * ui_soundset = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_soundtxt = NULL;
lv_obj_t * ui_soundcont = NULL;
lv_obj_t * ui_soundslider = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_soundtxt2 = NULL;
lv_obj_t * ui_soundval = NULL;
lv_obj_t * ui_soundcont2 = NULL;
lv_obj_t * ui_mute = NULL;
lv_obj_t * ui_mutetxt = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_soundcont3 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_soundtxt3 = NULL;
lv_obj_t * ui_mutetouch = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_soundset_screen_init(void)
{
    ui_soundset = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_soundset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundset, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_soundset);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 38);
    lv_obj_set_x(ui_Button4, -203);
    lv_obj_set_y(ui_Button4, -113);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_image_create(ui_Button4);
    lv_image_set_src(ui_Image25, &ui_img_1385604958);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundtxt = lv_label_create(ui_soundset);
    lv_obj_set_width(ui_soundtxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundtxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundtxt, 0);
    lv_obj_set_y(ui_soundtxt, -116);
    lv_obj_set_align(ui_soundtxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundtxt, _("sound"));
    lv_obj_set_style_text_color(ui_soundtxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soundtxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundcont = lv_obj_create(ui_soundset);
    lv_obj_set_width(ui_soundcont, 440);
    lv_obj_set_height(ui_soundcont, 65);
    lv_obj_set_x(ui_soundcont, 0);
    lv_obj_set_y(ui_soundcont, -45);
    lv_obj_set_align(ui_soundcont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_soundcont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundcont, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundcont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_soundcont, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_soundcont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundslider = lv_slider_create(ui_soundset);
    lv_slider_set_value(ui_soundslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_soundslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_soundslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_soundslider, 231);
    lv_obj_set_height(ui_soundslider, 5);
    lv_obj_set_x(ui_soundslider, 41);
    lv_obj_set_y(ui_soundslider, -45);
    lv_obj_set_align(ui_soundslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_soundslider, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_soundslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_soundslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_soundslider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_soundslider,
                                                                                                  lv_obj_get_style_pad_right(ui_soundslider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image24 = lv_image_create(ui_soundset);
    lv_image_set_src(ui_Image24, &ui_img_1475031593);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image24, -193);
    lv_obj_set_y(ui_Image24, -45);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundtxt2 = lv_label_create(ui_soundset);
    lv_obj_set_width(ui_soundtxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundtxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundtxt2, -122);
    lv_obj_set_y(ui_soundtxt2, -45);
    lv_obj_set_align(ui_soundtxt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundtxt2, _("sound"));
    lv_obj_set_style_text_color(ui_soundtxt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundtxt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soundtxt2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundval = lv_label_create(ui_soundset);
    lv_obj_set_width(ui_soundval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundval, 193);
    lv_obj_set_y(ui_soundval, -44);
    lv_obj_set_align(ui_soundval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundval, "100%");
    lv_obj_set_style_text_color(ui_soundval, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soundval, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundcont2 = lv_obj_create(ui_soundset);
    lv_obj_set_width(ui_soundcont2, 440);
    lv_obj_set_height(ui_soundcont2, 65);
    lv_obj_set_x(ui_soundcont2, 0);
    lv_obj_set_y(ui_soundcont2, 25);
    lv_obj_set_align(ui_soundcont2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_soundcont2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundcont2, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundcont2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_soundcont2, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_soundcont2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mute = lv_switch_create(ui_soundcont2);
    lv_obj_set_width(ui_mute, 50);
    lv_obj_set_height(ui_mute, 25);
    lv_obj_set_x(ui_mute, 180);
    lv_obj_set_y(ui_mute, 0);
    lv_obj_set_align(ui_mute, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_mute, lv_color_hex(0x2D3138), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mutetxt = lv_label_create(ui_soundcont2);
    lv_obj_set_width(ui_mutetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mutetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mutetxt, -123);
    lv_obj_set_y(ui_mutetxt, 0);
    lv_obj_set_align(ui_mutetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mutetxt, _("mute"));
    lv_obj_set_style_text_color(ui_mutetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mutetxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mutetxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_image_create(ui_soundcont2);
    lv_image_set_src(ui_Image26, &ui_img_1176085953);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image26, -190);
    lv_obj_set_y(ui_Image26, 0);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundcont3 = lv_obj_create(ui_soundset);
    lv_obj_set_width(ui_soundcont3, 440);
    lv_obj_set_height(ui_soundcont3, 65);
    lv_obj_set_x(ui_soundcont3, 0);
    lv_obj_set_y(ui_soundcont3, 95);
    lv_obj_set_align(ui_soundcont3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_soundcont3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundcont3, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundcont3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_soundcont3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_soundcont3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_image_create(ui_soundset);
    lv_image_set_src(ui_Image27, &ui_img_443122641);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image27, -192);
    lv_obj_set_y(ui_Image27, 97);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_soundtxt3 = lv_label_create(ui_soundset);
    lv_obj_set_width(ui_soundtxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundtxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundtxt3, -90);
    lv_obj_set_y(ui_soundtxt3, 97);
    lv_obj_set_align(ui_soundtxt3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soundtxt3, _("touch sound"));
    lv_obj_set_style_text_color(ui_soundtxt3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soundtxt3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soundtxt3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mutetouch = lv_switch_create(ui_soundset);
    lv_obj_set_width(ui_mutetouch, 50);
    lv_obj_set_height(ui_mutetouch, 25);
    lv_obj_set_x(ui_mutetouch, 182);
    lv_obj_set_y(ui_mutetouch, 97);
    lv_obj_set_align(ui_mutetouch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_mutetouch, lv_color_hex(0x2D3138), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mutetouch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    uic_soundset = ui_soundset;
    uic_soundtxt = ui_soundtxt;
    uic_soundslider = ui_soundslider;
    uic_soundtxt2 = ui_soundtxt2;
    uic_soundval = ui_soundval;
    uic_mute = ui_mute;
    uic_mutetxt = ui_mutetxt;
    uic_soundtxt3 = ui_soundtxt3;
    uic_mutetouch = ui_mutetouch;

}

void ui_soundset_screen_destroy(void)
{
    if(ui_soundset) lv_obj_del(ui_soundset);

    // NULL screen variables
    uic_soundset = NULL;
    ui_soundset = NULL;
    ui_Button4 = NULL;
    ui_Image25 = NULL;
    uic_soundtxt = NULL;
    ui_soundtxt = NULL;
    ui_soundcont = NULL;
    uic_soundslider = NULL;
    ui_soundslider = NULL;
    ui_Image24 = NULL;
    uic_soundtxt2 = NULL;
    ui_soundtxt2 = NULL;
    uic_soundval = NULL;
    ui_soundval = NULL;
    ui_soundcont2 = NULL;
    uic_mute = NULL;
    ui_mute = NULL;
    uic_mutetxt = NULL;
    ui_mutetxt = NULL;
    ui_Image26 = NULL;
    ui_soundcont3 = NULL;
    ui_Image27 = NULL;
    uic_soundtxt3 = NULL;
    ui_soundtxt3 = NULL;
    uic_mutetouch = NULL;
    ui_mutetouch = NULL;

}

void ui_soundset_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_soundtxt) && lv_obj_is_valid(ui_soundtxt)) lv_label_set_text(ui_soundtxt, _("sound"));
    if((ui_soundtxt2) && lv_obj_is_valid(ui_soundtxt2)) lv_label_set_text(ui_soundtxt2, _("sound"));
    if((ui_mutetxt) && lv_obj_is_valid(ui_mutetxt)) lv_label_set_text(ui_mutetxt, _("mute"));
    if((ui_soundtxt3) && lv_obj_is_valid(ui_soundtxt3)) lv_label_set_text(ui_soundtxt3, _("touch sound"));

}
