// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SOUNDSET_H
#define UI_SOUNDSET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_soundset
extern void ui_soundset_screen_init(void);
extern void ui_soundset_screen_destroy(void);
extern void ui_soundset_screen_relocalize(void);
extern lv_obj_t * ui_soundset;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_soundtxt;
extern lv_obj_t * ui_soundcont;
extern lv_obj_t * ui_soundslider;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_soundtxt2;
extern lv_obj_t * ui_soundval;
extern lv_obj_t * ui_soundcont2;
extern lv_obj_t * ui_mute;
extern lv_obj_t * ui_mutetxt;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_soundcont3;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_soundtxt3;
extern lv_obj_t * ui_mutetouch;
// CUSTOM VARIABLES
extern lv_obj_t * uic_soundset;
extern lv_obj_t * uic_soundtxt;
extern lv_obj_t * uic_soundslider;
extern lv_obj_t * uic_soundtxt2;
extern lv_obj_t * uic_soundval;
extern lv_obj_t * uic_mute;
extern lv_obj_t * uic_mutetxt;
extern lv_obj_t * uic_soundtxt3;
extern lv_obj_t * uic_mutetouch;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

