// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_txtbtn8;
lv_obj_t * uic_txtbtn7;
lv_obj_t * uic_txtbtn6;
lv_obj_t * uic_txtbtn5;
lv_obj_t * uic_txtbtn4;
lv_obj_t * uic_txtbtn1;
lv_obj_t * uic_changetoinfoset;
lv_obj_t * uic_changetoappset;
lv_obj_t * uic_changetotimeset;
lv_obj_t * uic_changetosoundset;
lv_obj_t * uic_changetolangset;
lv_obj_t * uic_changetowifiset;
lv_obj_t * uic_settext;
lv_obj_t * uic_settings;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_wifi2 = NULL;
lv_obj_t * ui_settext = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_changetowifiset = NULL;
lv_obj_t * ui_changetolangset = NULL;
lv_obj_t * ui_changetosoundset = NULL;
lv_obj_t * ui_changetotimeset = NULL;
lv_obj_t * ui_changetoappset = NULL;
lv_obj_t * ui_changetoinfoset = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_txtbtn1 = NULL;
lv_obj_t * ui_txtbtn4 = NULL;
lv_obj_t * ui_txtbtn5 = NULL;
lv_obj_t * ui_txtbtn6 = NULL;
lv_obj_t * ui_txtbtn7 = NULL;
lv_obj_t * ui_txtbtn8 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_main_screen_init);
    }
    

}

void ui_event_changetowifiset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiset, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiset_screen_init);
    }
}

void ui_event_changetolangset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_langset, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_langset_screen_init);
    }
}

void ui_event_changetosoundset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_soundset, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_soundset_screen_init);
    }
}

void ui_event_changetotimeset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_date, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_date_screen_init);
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi2 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_wifi2, 19);
    lv_obj_set_height(ui_wifi2, 21);
    lv_obj_set_x(ui_wifi2, 198);
    lv_obj_set_y(ui_wifi2, -122);
    lv_obj_set_align(ui_wifi2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifi2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifi2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_wifi2, "");
    lv_obj_set_style_text_color(ui_wifi2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifi2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settext = lv_label_create(ui_settings);
    lv_obj_set_width(ui_settext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settext, 0);
    lv_obj_set_y(ui_settext, -120);
    lv_obj_set_align(ui_settext, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_settext, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settext, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_settext, _("settings"));
    lv_obj_set_style_text_color(ui_settext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_settings);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 38);
    lv_obj_set_x(ui_Button3, -202);
    lv_obj_set_y(ui_Button3, -114);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Button3);
    lv_image_set_src(ui_Image1, &ui_img_1385604958);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changetowifiset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetowifiset, 220);
    lv_obj_set_height(ui_changetowifiset, 58);
    lv_obj_set_x(ui_changetowifiset, -121);
    lv_obj_set_y(ui_changetowifiset, -52);
    lv_obj_set_align(ui_changetowifiset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetowifiset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetowifiset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetowifiset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetowifiset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetowifiset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetowifiset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetowifiset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetowifiset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetowifiset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetowifiset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetowifiset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetowifiset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetowifiset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetowifiset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetolangset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetolangset, 220);
    lv_obj_set_height(ui_changetolangset, 58);
    lv_obj_set_x(ui_changetolangset, -122);
    lv_obj_set_y(ui_changetolangset, 20);
    lv_obj_set_align(ui_changetolangset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetolangset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetolangset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetolangset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetolangset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetolangset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetolangset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetolangset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetolangset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetolangset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetolangset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetolangset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetolangset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetolangset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetolangset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetosoundset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetosoundset, 220);
    lv_obj_set_height(ui_changetosoundset, 58);
    lv_obj_set_x(ui_changetosoundset, -122);
    lv_obj_set_y(ui_changetosoundset, 92);
    lv_obj_set_align(ui_changetosoundset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetosoundset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetosoundset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetosoundset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetosoundset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetosoundset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetosoundset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetosoundset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetosoundset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetosoundset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetosoundset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetosoundset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetosoundset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetosoundset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetosoundset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetotimeset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetotimeset, 216);
    lv_obj_set_height(ui_changetotimeset, 58);
    lv_obj_set_x(ui_changetotimeset, 120);
    lv_obj_set_y(ui_changetotimeset, -52);
    lv_obj_set_align(ui_changetotimeset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetotimeset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetotimeset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetotimeset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetotimeset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetotimeset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetotimeset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetotimeset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetotimeset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetotimeset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetotimeset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetotimeset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetotimeset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetotimeset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetotimeset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetoappset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetoappset, 220);
    lv_obj_set_height(ui_changetoappset, 58);
    lv_obj_set_x(ui_changetoappset, 120);
    lv_obj_set_y(ui_changetoappset, 20);
    lv_obj_set_align(ui_changetoappset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetoappset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetoappset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetoappset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetoappset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetoappset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetoappset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetoappset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetoappset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetoappset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetoappset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetoappset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetoappset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetoappset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetoappset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changetoinfoset = lv_button_create(ui_settings);
    lv_obj_set_width(ui_changetoinfoset, 220);
    lv_obj_set_height(ui_changetoinfoset, 58);
    lv_obj_set_x(ui_changetoinfoset, 120);
    lv_obj_set_y(ui_changetoinfoset, 92);
    lv_obj_set_align(ui_changetoinfoset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changetoinfoset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changetoinfoset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changetoinfoset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changetoinfoset, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changetoinfoset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changetoinfoset, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changetoinfoset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changetoinfoset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changetoinfoset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changetoinfoset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_changetoinfoset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_changetoinfoset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_changetoinfoset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_changetoinfoset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image2, &ui_img_567465477);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -205);
    lv_obj_set_y(ui_Image2, 20);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image3, &ui_img_1687889417);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -206);
    lv_obj_set_y(ui_Image3, -51);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image4, &ui_img_1475031593);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -201);
    lv_obj_set_y(ui_Image4, 93);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image7, &ui_img_1198081141);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 42);
    lv_obj_set_y(ui_Image7, -52);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image8, &ui_img_1958657997);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 39);
    lv_obj_set_y(ui_Image8, 21);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image9, &ui_img_668791536);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 41);
    lv_obj_set_y(ui_Image9, 94);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtbtn1 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn1, -151);
    lv_obj_set_y(ui_txtbtn1, -52);
    lv_obj_set_align(ui_txtbtn1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn1, _("wifi"));
    lv_obj_set_style_text_color(ui_txtbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn4 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn4, -128);
    lv_obj_set_y(ui_txtbtn4, 20);
    lv_obj_set_align(ui_txtbtn4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn4, _("language"));
    lv_obj_set_style_text_color(ui_txtbtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn5 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn5, -141);
    lv_obj_set_y(ui_txtbtn5, 91);
    lv_obj_set_align(ui_txtbtn5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn5, _("sound"));
    lv_obj_set_style_text_color(ui_txtbtn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn6 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn6, 118);
    lv_obj_set_y(ui_txtbtn6, -51);
    lv_obj_set_align(ui_txtbtn6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn6, _("time&date"));
    lv_obj_set_style_text_color(ui_txtbtn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn7 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn7, 117);
    lv_obj_set_y(ui_txtbtn7, 22);
    lv_obj_set_align(ui_txtbtn7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn7, "shifti app");
    lv_obj_set_style_text_color(ui_txtbtn7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbtn8 = lv_label_create(ui_settings);
    lv_obj_set_width(ui_txtbtn8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtbtn8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtbtn8, 101);
    lv_obj_set_y(ui_txtbtn8, 94);
    lv_obj_set_align(ui_txtbtn8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_txtbtn8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_txtbtn8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_txtbtn8, _("about"));
    lv_obj_set_style_text_color(ui_txtbtn8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtbtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtbtn8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image10, &ui_img_1832640421);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -34);
    lv_obj_set_y(ui_Image10, -51);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image11, &ui_img_1832640421);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -34);
    lv_obj_set_y(ui_Image11, 20);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image12, &ui_img_1832640421);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, -33);
    lv_obj_set_y(ui_Image12, 93);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image13, &ui_img_1832640421);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 207);
    lv_obj_set_y(ui_Image13, -52);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image14, &ui_img_1832640421);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, 209);
    lv_obj_set_y(ui_Image14, 23);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_settings);
    lv_image_set_src(ui_Image15, &ui_img_1832640421);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 211);
    lv_obj_set_y(ui_Image15, 92);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetowifiset, ui_event_changetowifiset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetolangset, ui_event_changetolangset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetosoundset, ui_event_changetosoundset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changetotimeset, ui_event_changetotimeset, LV_EVENT_ALL, NULL);
    uic_settings = ui_settings;
    uic_settext = ui_settext;
    uic_changetowifiset = ui_changetowifiset;
    uic_changetolangset = ui_changetolangset;
    uic_changetosoundset = ui_changetosoundset;
    uic_changetotimeset = ui_changetotimeset;
    uic_changetoappset = ui_changetoappset;
    uic_changetoinfoset = ui_changetoinfoset;
    uic_txtbtn1 = ui_txtbtn1;
    uic_txtbtn4 = ui_txtbtn4;
    uic_txtbtn5 = ui_txtbtn5;
    uic_txtbtn6 = ui_txtbtn6;
    uic_txtbtn7 = ui_txtbtn7;
    uic_txtbtn8 = ui_txtbtn8;

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    uic_settings = NULL;
    ui_settings = NULL;
    ui_wifi2 = NULL;
    uic_settext = NULL;
    ui_settext = NULL;
    ui_Button3 = NULL;
    ui_Image1 = NULL;
    uic_changetowifiset = NULL;
    ui_changetowifiset = NULL;
    uic_changetolangset = NULL;
    ui_changetolangset = NULL;
    uic_changetosoundset = NULL;
    ui_changetosoundset = NULL;
    uic_changetotimeset = NULL;
    ui_changetotimeset = NULL;
    uic_changetoappset = NULL;
    ui_changetoappset = NULL;
    uic_changetoinfoset = NULL;
    ui_changetoinfoset = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    uic_txtbtn1 = NULL;
    ui_txtbtn1 = NULL;
    uic_txtbtn4 = NULL;
    ui_txtbtn4 = NULL;
    uic_txtbtn5 = NULL;
    ui_txtbtn5 = NULL;
    uic_txtbtn6 = NULL;
    ui_txtbtn6 = NULL;
    uic_txtbtn7 = NULL;
    ui_txtbtn7 = NULL;
    uic_txtbtn8 = NULL;
    ui_txtbtn8 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;

}

void ui_settings_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_settext) && lv_obj_is_valid(ui_settext)) lv_label_set_text(ui_settext, _("settings"));
    if((ui_txtbtn1) && lv_obj_is_valid(ui_txtbtn1)) lv_label_set_text(ui_txtbtn1, _("wifi"));
    if((ui_txtbtn4) && lv_obj_is_valid(ui_txtbtn4)) lv_label_set_text(ui_txtbtn4, _("language"));
    if((ui_txtbtn5) && lv_obj_is_valid(ui_txtbtn5)) lv_label_set_text(ui_txtbtn5, _("sound"));
    if((ui_txtbtn6) && lv_obj_is_valid(ui_txtbtn6)) lv_label_set_text(ui_txtbtn6, _("time&date"));
    if((ui_txtbtn8) && lv_obj_is_valid(ui_txtbtn8)) lv_label_set_text(ui_txtbtn8, _("about"));

}
