// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WIFISET_H
#define UI_WIFISET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiset
extern void ui_wifiset_screen_init(void);
extern void ui_wifiset_screen_destroy(void);
extern void ui_wifiset_screen_relocalize(void);
extern lv_obj_t * ui_wifiset;
extern lv_obj_t * ui_wifitxt;
extern lv_obj_t * ui_searchwifi;
extern lv_obj_t * ui_Image20;
extern void ui_event_backtosettings(lv_event_t * e);
extern lv_obj_t * ui_backtosettings;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_currentnetwork;
extern lv_obj_t * ui_current;
extern lv_obj_t * ui_available;
extern lv_obj_t * ui_wificontainer;
extern lv_obj_t * ui_wifiItemTemplate;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_lblWifiName;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_loadingoverlay;
extern lv_obj_t * ui_loading;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_loadingbar;
extern lv_obj_t * ui_Image22;
// CUSTOM VARIABLES
extern lv_obj_t * uic_wifiset;
extern lv_obj_t * uic_wifitxt;
extern lv_obj_t * uic_searchwifi;
extern lv_obj_t * uic_backtosettings;
extern lv_obj_t * uic_currentnetwork;
extern lv_obj_t * uic_current;
extern lv_obj_t * uic_available;
extern lv_obj_t * uic_wificontainer;
extern lv_obj_t * uic_wifiItemTemplate;
extern lv_obj_t * uic_lblWifiName;
extern lv_obj_t * uic_loadingoverlay;
extern lv_obj_t * uic_loading;
extern lv_obj_t * uic_loadingbar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

