// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_loadingbar;
lv_obj_t * uic_loading;
lv_obj_t * uic_loadingoverlay;
lv_obj_t * uic_lblWifiName;
lv_obj_t * uic_wifiItemTemplate;
lv_obj_t * uic_wificontainer;
lv_obj_t * uic_available;
lv_obj_t * uic_current;
lv_obj_t * uic_currentnetwork;
lv_obj_t * uic_backtosettings;
lv_obj_t * uic_searchwifi;
lv_obj_t * uic_wifitxt;
lv_obj_t * uic_wifiset;
lv_obj_t * ui_wifiset = NULL;
lv_obj_t * ui_wifitxt = NULL;
lv_obj_t * ui_searchwifi = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_backtosettings = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_currentnetwork = NULL;
lv_obj_t * ui_current = NULL;
lv_obj_t * ui_available = NULL;
lv_obj_t * ui_wificontainer = NULL;
lv_obj_t * ui_wifiItemTemplate = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_lblWifiName = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_loadingoverlay = NULL;
lv_obj_t * ui_loading = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_loadingbar = NULL;
lv_obj_t * ui_Image22 = NULL;
// event funtions
void ui_event_backtosettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_wifiset_screen_init(void)
{
    ui_wifiset = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifiset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiset, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifitxt = lv_label_create(ui_wifiset);
    lv_obj_set_width(ui_wifitxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifitxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifitxt, 0);
    lv_obj_set_y(ui_wifitxt, -116);
    lv_obj_set_align(ui_wifitxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifitxt, _("wifi"));
    lv_obj_set_style_text_color(ui_wifitxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifitxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifitxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_searchwifi = lv_button_create(ui_wifiset);
    lv_obj_set_width(ui_searchwifi, 50);
    lv_obj_set_height(ui_searchwifi, 38);
    lv_obj_set_x(ui_searchwifi, 204);
    lv_obj_set_y(ui_searchwifi, -114);
    lv_obj_set_align(ui_searchwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_searchwifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_searchwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_searchwifi, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_searchwifi, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_searchwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_searchwifi, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_searchwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_searchwifi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_searchwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_searchwifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_searchwifi);
    lv_image_set_src(ui_Image20, &ui_img_310155206);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backtosettings = lv_button_create(ui_wifiset);
    lv_obj_set_width(ui_backtosettings, 50);
    lv_obj_set_height(ui_backtosettings, 38);
    lv_obj_set_x(ui_backtosettings, -203);
    lv_obj_set_y(ui_backtosettings, -114);
    lv_obj_set_align(ui_backtosettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtosettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backtosettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtosettings, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtosettings, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtosettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtosettings, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtosettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtosettings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backtosettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backtosettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_image_create(ui_backtosettings);
    lv_image_set_src(ui_Image17, &ui_img_1385604958);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_Panel5, 480);
    lv_obj_set_height(ui_Panel5, 218);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 23);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x0B0D12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel6, 440);
    lv_obj_set_height(ui_Panel6, 50);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -52);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_image_create(ui_Panel6);
    lv_image_set_src(ui_Image18, &ui_img_1799210772);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, -186);
    lv_obj_set_y(ui_Image18, 0);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_currentnetwork = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_currentnetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentnetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentnetwork, 31);
    lv_obj_set_y(ui_currentnetwork, 1);
    lv_obj_set_align(ui_currentnetwork, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_currentnetwork, "my_netowrk");
    lv_obj_set_style_text_color(ui_currentnetwork, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentnetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentnetwork, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_current = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_current, -158);
    lv_obj_set_y(ui_current, -88);
    lv_obj_set_align(ui_current, LV_ALIGN_CENTER);
    lv_label_set_text(ui_current, _("current network"));
    lv_obj_set_style_text_color(ui_current, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_current, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_available = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_available, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_available, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_available, -158);
    lv_obj_set_y(ui_available, -3);
    lv_obj_set_align(ui_available, LV_ALIGN_CENTER);
    lv_label_set_text(ui_available, _("available network"));
    lv_obj_set_style_text_color(ui_available, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_available, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_available, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wificontainer = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_wificontainer, 440);
    lv_obj_set_height(ui_wificontainer, 42);
    lv_obj_set_x(ui_wificontainer, 2);
    lv_obj_set_y(ui_wificontainer, 108);
    lv_obj_remove_flag(ui_wificontainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wificontainer, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wificontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wificontainer, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wificontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiItemTemplate = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_wifiItemTemplate, 420);
    lv_obj_set_height(ui_wifiItemTemplate, 28);
    lv_obj_set_x(ui_wifiItemTemplate, -3);
    lv_obj_set_y(ui_wifiItemTemplate, 53);
    lv_obj_set_align(ui_wifiItemTemplate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiItemTemplate, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifiItemTemplate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiItemTemplate, lv_color_hex(0x141922), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiItemTemplate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiItemTemplate, lv_color_hex(0x2A303B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiItemTemplate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_wifiItemTemplate);
    lv_image_set_src(ui_Image19, &ui_img_1799210772);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, -186);
    lv_obj_set_y(ui_Image19, 0);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWifiName = lv_label_create(ui_wifiItemTemplate);
    lv_obj_set_width(ui_lblWifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiName, -127);
    lv_obj_set_y(ui_lblWifiName, 0);
    lv_obj_set_align(ui_lblWifiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiName, "my_netowrk");
    lv_obj_set_style_text_color(ui_lblWifiName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiName, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_wifiItemTemplate);
    lv_image_set_src(ui_Image16, &ui_img_1832640421);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, 194);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadingoverlay = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_loadingoverlay, lv_pct(103));
    lv_obj_set_height(ui_loadingoverlay, lv_pct(110));
    lv_obj_set_x(ui_loadingoverlay, -4);
    lv_obj_set_y(ui_loadingoverlay, 4);
    lv_obj_set_align(ui_loadingoverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loadingoverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_loadingoverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loadingoverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingoverlay, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loadingoverlay, lv_color_hex(0x4A5670), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loadingoverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loading = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_loading, 200);
    lv_obj_set_height(ui_loading, 100);
    lv_obj_set_x(ui_loading, 2);
    lv_obj_set_y(ui_loading, 0);
    lv_obj_set_align(ui_loading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_loading, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loading, lv_color_hex(0x232A3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loading, lv_color_hex(0x2A3C58), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_loading);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 7);
    lv_obj_set_y(ui_Label2, -17);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "scaning...");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadingbar = lv_bar_create(ui_loading);
    lv_bar_set_value(ui_loadingbar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_loadingbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_loadingbar, 150);
    lv_obj_set_height(ui_loadingbar, 10);
    lv_obj_set_align(ui_loadingbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_loadingbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loadingbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loadingbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_loadingbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_loadingbar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_loadingbar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_loadingbar,
                                                                                                 lv_obj_get_style_pad_right(ui_loadingbar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image22 = lv_image_create(ui_loading);
    lv_image_set_src(ui_Image22, &ui_img_310155206);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, -43);
    lv_obj_set_y(ui_Image22, -19);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_backtosettings, ui_event_backtosettings, LV_EVENT_ALL, NULL);
    uic_wifiset = ui_wifiset;
    uic_wifitxt = ui_wifitxt;
    uic_searchwifi = ui_searchwifi;
    uic_backtosettings = ui_backtosettings;
    uic_currentnetwork = ui_currentnetwork;
    uic_current = ui_current;
    uic_available = ui_available;
    uic_wificontainer = ui_wificontainer;
    uic_wifiItemTemplate = ui_wifiItemTemplate;
    uic_lblWifiName = ui_lblWifiName;
    uic_loadingoverlay = ui_loadingoverlay;
    uic_loading = ui_loading;
    uic_loadingbar = ui_loadingbar;

}

void ui_wifiset_screen_destroy(void)
{
    if(ui_wifiset) lv_obj_del(ui_wifiset);

    // NULL screen variables
    uic_wifiset = NULL;
    ui_wifiset = NULL;
    uic_wifitxt = NULL;
    ui_wifitxt = NULL;
    uic_searchwifi = NULL;
    ui_searchwifi = NULL;
    ui_Image20 = NULL;
    uic_backtosettings = NULL;
    ui_backtosettings = NULL;
    ui_Image17 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    ui_Image18 = NULL;
    uic_currentnetwork = NULL;
    ui_currentnetwork = NULL;
    uic_current = NULL;
    ui_current = NULL;
    uic_available = NULL;
    ui_available = NULL;
    uic_wificontainer = NULL;
    ui_wificontainer = NULL;
    uic_wifiItemTemplate = NULL;
    ui_wifiItemTemplate = NULL;
    ui_Image19 = NULL;
    uic_lblWifiName = NULL;
    ui_lblWifiName = NULL;
    ui_Image16 = NULL;
    uic_loadingoverlay = NULL;
    ui_loadingoverlay = NULL;
    uic_loading = NULL;
    ui_loading = NULL;
    ui_Label2 = NULL;
    uic_loadingbar = NULL;
    ui_loadingbar = NULL;
    ui_Image22 = NULL;

}

void ui_wifiset_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_wifitxt) && lv_obj_is_valid(ui_wifitxt)) lv_label_set_text(ui_wifitxt, _("wifi"));
    if((ui_current) && lv_obj_is_valid(ui_current)) lv_label_set_text(ui_current, _("current network"));
    if((ui_available) && lv_obj_is_valid(ui_available)) lv_label_set_text(ui_available, _("available network"));

}
